/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmContasPagar.java
 *
 * Created on 06/02/2010, 14:19:37
 */
package Relatorios;

import sae.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.*;
import Classes.claAcessoDados;
import Classes.claVariaveis;
import Classes.claFuncoes;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import Classes.claVariaveis;
import Classes.claAcessoDados;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.text.html.parser.Parser;

import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.*;


/**
 *
 * @author Thiago
 */
public class RelContasReceber extends javax.swing.JDialog {

    claVariaveis variaveis = new claVariaveis();
    claAcessoDados AcessoDados = new claAcessoDados();
    claFuncoes funcoes = new claFuncoes();
    private ResultSet rs;

    /** Creates new form FrmContasPagar */
    public RelContasReceber(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        funcoes.F_AtribuirClasse(rootPane);
        btnImprimir.setFocusTraversalKeysEnabled(false);
        txtCodigoEmpresaID.requestFocus();

    }
    public static int vm_ID;


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        btnImprimir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        btnPesquisaEmpresaID = new javax.swing.JButton();
        txtTipoDeDocumentoDescricao = new javax.swing.JTextField();
        txtTipoDeDocumentoID = new javax.swing.JTextField();
        btnPesquisaTipoDocumentoID = new javax.swing.JButton();
        txtBancoID = new javax.swing.JTextField();
        btnPesquisaBancoID = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtParceiro = new javax.swing.JTextField();
        txtFormaDePagamentoDescricao = new javax.swing.JTextField();
        txtCodigoParceiroID = new javax.swing.JTextField();
        btnPesquisaFormaPagamentoID = new javax.swing.JButton();
        btnPesquisaParceiroID = new javax.swing.JButton();
        txtFormaDePagamentoID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtBancoDescricao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoEmpresaID = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtVencimentoIni = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        txtVencimentoFim = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        cbPosicao = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relação de Contas a Receber");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imprimir.gif"))); // NOI18N
        btnImprimir.setToolTipText("Imprimir");
        btnImprimir.setBorderPainted(false);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sair.gif"))); // NOI18N
        btnSair.setBorderPainted(false);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE)
            .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel18.setText("Conta Bancária :");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel3.setText("Parceiro :");

        txtEmpresa.setEditable(false);
        txtEmpresa.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtEmpresa.setForeground(new java.awt.Color(102, 102, 255));
        txtEmpresa.setFocusable(false);
        txtEmpresa.setRequestFocusEnabled(false);

        btnPesquisaEmpresaID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.gif"))); // NOI18N
        btnPesquisaEmpresaID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPesquisaEmpresaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaEmpresaIDActionPerformed(evt);
            }
        });

        txtTipoDeDocumentoDescricao.setEditable(false);
        txtTipoDeDocumentoDescricao.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtTipoDeDocumentoDescricao.setForeground(new java.awt.Color(102, 102, 255));
        txtTipoDeDocumentoDescricao.setFocusable(false);
        txtTipoDeDocumentoDescricao.setRequestFocusEnabled(false);

        txtTipoDeDocumentoID.setColumns(8);
        txtTipoDeDocumentoID.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtTipoDeDocumentoID.setToolTipText("Código");
        txtTipoDeDocumentoID.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtTipoDeDocumentoID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTipoDeDocumentoIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTipoDeDocumentoIDFocusLost(evt);
            }
        });
        txtTipoDeDocumentoID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTipoDeDocumentoIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTipoDeDocumentoIDKeyReleased(evt);
            }
        });

        btnPesquisaTipoDocumentoID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.gif"))); // NOI18N
        btnPesquisaTipoDocumentoID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPesquisaTipoDocumentoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaTipoDocumentoIDActionPerformed(evt);
            }
        });

        txtBancoID.setColumns(8);
        txtBancoID.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtBancoID.setToolTipText("Código");
        txtBancoID.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtBancoID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBancoIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBancoIDFocusLost(evt);
            }
        });
        txtBancoID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBancoIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBancoIDKeyReleased(evt);
            }
        });

        btnPesquisaBancoID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.gif"))); // NOI18N
        btnPesquisaBancoID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPesquisaBancoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaBancoIDActionPerformed(evt);
            }
        });
        btnPesquisaBancoID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnPesquisaBancoIDFocusLost(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel12.setText("Tipo de Documento :");

        txtParceiro.setEditable(false);
        txtParceiro.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtParceiro.setForeground(new java.awt.Color(102, 102, 255));
        txtParceiro.setFocusable(false);
        txtParceiro.setRequestFocusEnabled(false);

        txtFormaDePagamentoDescricao.setEditable(false);
        txtFormaDePagamentoDescricao.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtFormaDePagamentoDescricao.setForeground(new java.awt.Color(102, 102, 255));
        txtFormaDePagamentoDescricao.setFocusable(false);
        txtFormaDePagamentoDescricao.setRequestFocusEnabled(false);

        txtCodigoParceiroID.setColumns(8);
        txtCodigoParceiroID.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtCodigoParceiroID.setToolTipText("Código");
        txtCodigoParceiroID.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtCodigoParceiroID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoParceiroIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoParceiroIDFocusLost(evt);
            }
        });
        txtCodigoParceiroID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoParceiroIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoParceiroIDKeyReleased(evt);
            }
        });

        btnPesquisaFormaPagamentoID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.gif"))); // NOI18N
        btnPesquisaFormaPagamentoID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPesquisaFormaPagamentoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaFormaPagamentoIDActionPerformed(evt);
            }
        });

        btnPesquisaParceiroID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.gif"))); // NOI18N
        btnPesquisaParceiroID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPesquisaParceiroID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaParceiroIDActionPerformed(evt);
            }
        });

        txtFormaDePagamentoID.setColumns(8);
        txtFormaDePagamentoID.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtFormaDePagamentoID.setToolTipText("Código");
        txtFormaDePagamentoID.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtFormaDePagamentoID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFormaDePagamentoIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFormaDePagamentoIDFocusLost(evt);
            }
        });
        txtFormaDePagamentoID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFormaDePagamentoIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFormaDePagamentoIDKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel10.setText("Forma de Pgto :");

        txtBancoDescricao.setEditable(false);
        txtBancoDescricao.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtBancoDescricao.setForeground(new java.awt.Color(102, 102, 255));
        txtBancoDescricao.setFocusable(false);
        txtBancoDescricao.setRequestFocusEnabled(false);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel2.setText("Empresa :");

        txtCodigoEmpresaID.setColumns(8);
        txtCodigoEmpresaID.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtCodigoEmpresaID.setToolTipText("Código");
        txtCodigoEmpresaID.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtCodigoEmpresaID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoEmpresaIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoEmpresaIDFocusLost(evt);
            }
        });
        txtCodigoEmpresaID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoEmpresaIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoEmpresaIDKeyReleased(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vencimento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel7.setText("Inicial:");

        try {
            txtVencimentoIni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtVencimentoIni.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtVencimentoIni.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtVencimentoIni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVencimentoIniFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVencimentoIniFocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel9.setText("Final:");

        try {
            txtVencimentoFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtVencimentoFim.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtVencimentoFim.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtVencimentoFim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVencimentoFimFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVencimentoFimFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(6, 6, 6)
                .addComponent(txtVencimentoIni, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(3, 3, 3)
                .addComponent(txtVencimentoFim, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtVencimentoIni, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtVencimentoFim, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Posição Financeira", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10))); // NOI18N

        cbPosicao.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        cbPosicao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TODOS", "A REALIZAR", "REALIZADO", "VENCIDOS" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(cbPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(62, 62, 62)
                                .addComponent(txtCodigoEmpresaID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisaEmpresaID, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(30, 30, 30)
                                        .addComponent(txtBancoID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPesquisaBancoID, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel3))
                                                .addGap(35, 35, 35)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtFormaDePagamentoID, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                                    .addComponent(txtCodigoParceiroID, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtTipoDeDocumentoID, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnPesquisaFormaPagamentoID, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnPesquisaParceiroID, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnPesquisaTipoDocumentoID, javax.swing.GroupLayout.DEFAULT_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBancoDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                                    .addComponent(txtParceiro, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                                    .addComponent(txtFormaDePagamentoDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                                    .addComponent(txtTipoDeDocumentoDescricao))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesquisaEmpresaID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoEmpresaID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesquisaParceiroID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodigoParceiroID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(txtParceiro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtFormaDePagamentoID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFormaDePagamentoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisaFormaPagamentoID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtTipoDeDocumentoID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPesquisaTipoDocumentoID, javax.swing.GroupLayout.DEFAULT_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoDeDocumentoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBancoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(txtBancoID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPesquisaBancoID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtCodigoEmpresaIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoEmpresaIDFocusLost
        // TODO add your handling code here:
        // if (txtCodigoEmpresaID.getText().equals(null) || (txtCodigoEmpresaID.getText().equals("")))
        //    {
        //        txtCodigoEmpresaID.setText("1");

        //    }
        if (!txtCodigoEmpresaID.getText().equals("")) {
            String vmCampos = "*";
            String vmCondicao_Consulta = " WHERE emp_codigo_id = " + txtCodigoEmpresaID.getText();
            try {
                rs = AcessoDados.Selecao("empresas", vmCampos, vmCondicao_Consulta);
                if (!rs.next()) {
                    JOptionPane.showMessageDialog(null, "Empresa não cadastrada no sistema");
                    txtCodigoEmpresaID.setText(null);
                    txtEmpresa.setText(null);
                    txtEmpresa.requestFocus();
                    return;
                }
                txtEmpresa.setText(rs.getString("emp_nome"));
                txtCodigoParceiroID.requestFocus();
                rs.close();
            } catch (Exception e) {
                e.printStackTrace();
            }

        } else {
            txtEmpresa.setText(null);
        }
    }//GEN-LAST:event_txtCodigoEmpresaIDFocusLost

    private void txtCodigoParceiroIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoParceiroIDFocusLost
        // TODO add your handling code here:
        if (!txtCodigoParceiroID.getText().equals("")) {
            String vmCampos = "*";
            String vmCondicao_Consulta = " WHERE par_codigo_id = " + txtCodigoParceiroID.getText();
            try {
                rs = AcessoDados.Selecao("parceiros", vmCampos, vmCondicao_Consulta);
                if (!rs.next()) {
                    JOptionPane.showMessageDialog(null, "Parceiro não cadastrado no sistema");
                    txtCodigoParceiroID.setText(null);
                    txtParceiro.setText(null);
                    txtParceiro.requestFocus();
                    return;
                }
                txtParceiro.setText(rs.getString("par_nome_razao_social"));
                rs.close();
            } catch (Exception e) {
                e.printStackTrace();
            }

        } else {
            txtParceiro.setText(null);
        }
    }//GEN-LAST:event_txtCodigoParceiroIDFocusLost

    private void txtFormaDePagamentoIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFormaDePagamentoIDFocusLost
        // TODO add your handling code here:
        if (!txtFormaDePagamentoID.getText().equals("")) {
            String vmCampos = "*";
            String vmCondicao_Consulta = " WHERE fpgto_codigo_id = " + txtFormaDePagamentoID.getText();
            try {
                rs = AcessoDados.Selecao("Forma_de_Pagamento", vmCampos, vmCondicao_Consulta);
                if (!rs.next()) {
                    JOptionPane.showMessageDialog(null, "Forma de Pagamento não cadastrada no sistema");
                    txtFormaDePagamentoID.setText(null);
                    txtFormaDePagamentoDescricao.setText(null);
                    txtFormaDePagamentoID.requestFocus();
                    return;
                }
                txtFormaDePagamentoDescricao.setText(rs.getString("fpgto_descricao"));
                rs.close();
            } catch (Exception e) {
                e.printStackTrace();
            }

        } else {
            txtFormaDePagamentoDescricao.setText(null);
        }
    }//GEN-LAST:event_txtFormaDePagamentoIDFocusLost

    private void txtTipoDeDocumentoIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTipoDeDocumentoIDFocusLost
        // TODO add your handling code here:
        if (!txtTipoDeDocumentoID.getText().equals("")) {
            String vmCampos = "*";
            String vmCondicao_Consulta = " WHERE doc_codigo_id = " + txtTipoDeDocumentoID.getText();
            try {
                rs = AcessoDados.Selecao("tipo_documento", vmCampos, vmCondicao_Consulta);
                if (!rs.next()) {
                    JOptionPane.showMessageDialog(null, "Tipo de Documento não cadastrado no sistema");
                    txtTipoDeDocumentoID.setText(null);
                    txtTipoDeDocumentoDescricao.setText(null);
                    txtTipoDeDocumentoID.requestFocus();
                    return;
                }
                txtTipoDeDocumentoDescricao.setText(rs.getString("doc_descricao"));
                rs.close();
            } catch (Exception e) {
                e.printStackTrace();
            }

        } else {
            txtTipoDeDocumentoDescricao.setText(null);
        }

    }//GEN-LAST:event_txtTipoDeDocumentoIDFocusLost

    private void txtCodigoEmpresaIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoEmpresaIDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoEmpresaIDKeyReleased

    private void txtCodigoParceiroIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoParceiroIDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoParceiroIDKeyReleased

    private void txtFormaDePagamentoIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFormaDePagamentoIDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFormaDePagamentoIDKeyReleased

    private void txtTipoDeDocumentoIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTipoDeDocumentoIDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoDeDocumentoIDKeyReleased

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        if (txtEmpresa.getText().equals(null) || (txtEmpresa.getText().equals("")))
        {
           JOptionPane.showMessageDialog(null,"Favor informar a Empresa.");
           txtCodigoEmpresaID.requestFocus();
           return;
        }

      
        if (txtVencimentoIni.getText().equals("  /  /    ") || (txtVencimentoFim.getText().equals("  /  /    ")))
        {
           JOptionPane.showMessageDialog(null,"Período de vencimento inválido.");
           txtVencimentoIni.requestFocus();
           return;
        }
     
     
        String vParceiro = "TODOS OS PARCEIROS";
        String vmCampos = " CR.*, RCR.*, PAR.PAR_NOME_RAZAO_SOCIAL, COALESCE(rcr_valor_recebido,0) AS rcr_valor_recebido11,  ";
        vmCampos        += " CASE  WHEN CR.CR_VALOR_DOCUMENTO = " +
                           " (SELECT COALESCE(SUM(T.RCR_VALOR_RECEBIDO),0) AS TOTAL " +
                           " FROM RECEBIMENTO_CONTAS_RECEBER T WHERE T.RCR_CR_CODIGO_ID = CR.CR_CODIGO_ID) THEN RCR.RCR_VALOR_RECEBIDO ELSE CR.CR_VALOR_DOCUMENTO END AS VALOR_TITULO ";

        String vmCondicao_Consulta = " LEFT JOIN RECEBIMENTO_CONTAS_RECEBER RCR ON (RCR.rcr_cr_codigo_id = CR.CR_CODIGO_ID) "+
                                     " INNER JOIN PARCEIROS PAR ON (PAR.PAR_CODIGO_ID = CR.CR_PAR_CODIGO_ID)" +
                                     " WHERE CR_EMP_CODIGO_ID = " + txtCodigoEmpresaID.getText();

        if(cbPosicao.getSelectedIndex() == 1)
        {
            //vmCondicao_Consulta += " AND RCR.RCR_DATA_RECEBIMENTO IS NULL ";
            vmCondicao_Consulta += " AND CR.CR_VALOR_DOCUMENTO > (SELECT COALESCE(SUM(T.RCR_VALOR_RECEBIDO),0) AS TOTAL "
                                 + " FROM RECEBIMENTO_CONTAS_RECEBER T WHERE T.RCR_CR_CODIGO_ID = CR.CR_CODIGO_ID) ";
        }
        if(cbPosicao.getSelectedIndex() == 2)
        {
            vmCondicao_Consulta += " AND NOT RCR.RCR_DATA_RECEBIMENTO IS NULL ";
            vmCondicao_Consulta += " AND CR.CR_VALOR_DOCUMENTO = (SELECT COALESCE(SUM(T.RCR_VALOR_RECEBIDO),0) AS TOTAL "
                                 + " FROM RECEBIMENTO_CONTAS_RECEBER T WHERE T.RCR_CR_CODIGO_ID = CR.CR_CODIGO_ID) ";
        }
        if(cbPosicao.getSelectedIndex() == 3)
        {
          vmCondicao_Consulta += "   AND cr_data_vencimento < current_date ";
            vmCondicao_Consulta += " AND CR.CR_VALOR_DOCUMENTO > (SELECT COALESCE(SUM(T.RCR_VALOR_RECEBIDO),0) AS TOTAL "
                                 + " FROM RECEBIMENTO_CONTAS_RECEBER T WHERE T.RCR_CR_CODIGO_ID = CR.CR_CODIGO_ID) ";
        }
       
        vmCondicao_Consulta += " AND (CR_DATA_VENCIMENTO >= '"+txtVencimentoIni.getText()+"' AND CR_DATA_VENCIMENTO <= '"+txtVencimentoFim.getText()+"') ";
       


        if(!txtCodigoParceiroID.getText().equals(""))
        {
           vmCondicao_Consulta += " AND CR_PAR_CODIGO_ID = " + txtCodigoParceiroID.getText();
           vParceiro = txtParceiro.getText();
        }

        if(!txtFormaDePagamentoID.getText().equals(""))
           vmCondicao_Consulta += " AND cr_fpgto_codigo_id = " + txtFormaDePagamentoID.getText();


        if(!txtTipoDeDocumentoID.getText().equals(""))
           vmCondicao_Consulta += " AND cr_doc_codigo_id = " + txtTipoDeDocumentoID.getText();


        if(!txtBancoID.getText().equals(""))
           vmCondicao_Consulta += " AND cr_banc_codigo_id = " + txtBancoID.getText();


        vmCondicao_Consulta += " ORDER BY CR_DATA_VENCIMENTO";
        try
        {
        rs = AcessoDados.Selecao("CONTAS_RECEBER CR", vmCampos, vmCondicao_Consulta);
         }catch (Exception e) {
           e.printStackTrace();
        }

        HashMap map = new HashMap();
        

        try
        {
        map.put("pEmpresa",   "EMPRESA  : " + txtEmpresa.getText());
        map.put("pParceiro",  "PARCEIRO : " + vParceiro);
        map.put("pVencimento","PERIODO   : " + txtVencimentoIni.getText() + " a " + txtVencimentoFim.getText());
        map.put("pPosicao",   "POSIÇÃO  FINANCEIRA : " + cbPosicao.getSelectedItem().toString());
        String caminho = getClass().getResource("/Imagens/Logo.jpg").toString();
        map.put("pLogo", caminho);

        JasperReport jr = (JasperReport) JRLoader.loadObject(getClass().getClassLoader().getResource("Relatorios/RelContasReceber.jasper"));
        JRResultSetDataSource jrRS1 = new JRResultSetDataSource(rs);
        //JasperReport jr = (JasperReport) JRLoader.loadObject(arquivo);

        JasperPrint jp = JasperFillManager.fillReport(jr, map,jrRS1);
        JasperViewer jv = new JasperViewer(jp,false);
        JDialog viewer = new  JDialog(jv, true);
        viewer.setSize(1000,700);
        viewer.setLocationRelativeTo(null);
        viewer.getContentPane().add(jv.getContentPane());
        viewer.setVisible(true);

          }catch (Exception e) {
           e.printStackTrace();
        }

        txtEmpresa.requestFocus();


    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnPesquisaEmpresaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaEmpresaIDActionPerformed
        // TODO add your handling code here:
         variaveis.xColuna1 = "emp_codigo_id";
         variaveis.xColuna2 = "emp_nome";
         variaveis.xColuna3 = "emp_nome_fantasia";
         variaveis.xColuna4 = "emp_cnpj";
         variaveis.xColuna5 = "''";
         variaveis.xColuna6 = "''";
         variaveis.xColuna7 = "''";
         variaveis.xColuna8 = "''";
         variaveis.xColuna9 = "''";
         
         variaveis.xColunaNome1 = "Código";
         variaveis.xColunaNome2 = "Razão Social";
         variaveis.xColunaNome3 = "Fantasia";
         variaveis.xColunaNome4 = "CPF / CNPJ";
         variaveis.xColunaNome5 = "";
         variaveis.xColunaNome6 = "";
         variaveis.xColunaNome7 = "";
         variaveis.xColunaNome8 = "";
         variaveis.xColunaNome9 = "";
         
         variaveis.xColunaTamanho1 = 60;
         variaveis.xColunaTamanho2 = 450;
         variaveis.xColunaTamanho3 = 260;
         variaveis.xColunaTamanho4 = 120;
         variaveis.xColunaTamanho5 = 0;
         variaveis.xColunaTamanho6 = 0;
         variaveis.xColunaTamanho7 = 0;
         variaveis.xColunaTamanho8 = 0;
         variaveis.xColunaTamanho9 = 0;
         
         variaveis.xColunaStart = "emp_nome";
         variaveis.xColunaNomeStart = "Razão Social";
         variaveis.xTabela = "empresas";
         variaveis.xSql = ""; 
         
         FpesqPesquisa md = new FpesqPesquisa(null, true);
         Dimension d = new Dimension();   
         d.setSize(900, 480); 
         md.setSize(d);
         
         md.setTitle("Pesquisa Empresa - ENTER ou DUPLO CLICK no registro retorna dados.");

         md.setLocationRelativeTo(null);
         md.setVisible(true);

        if(!md.getRetorno().trim().equals("") ||!md.getRetorno().equals(null))
        {
          txtCodigoEmpresaID.setText((String) md.getRetorno());
        }

        txtCodigoEmpresaID.requestFocus();
        if (!txtCodigoEmpresaID.getText().equals("")) {
            String vmCampos = "*";
            String vmCondicao_Consulta = " WHERE emp_codigo_id = " + txtCodigoEmpresaID.getText();
            try {
                rs = AcessoDados.Selecao("empresas", vmCampos, vmCondicao_Consulta);
                rs.next();
                txtEmpresa.setText(rs.getString("emp_nome"));
                txtCodigoEmpresaID.requestFocus();
                rs.close();
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_btnPesquisaEmpresaIDActionPerformed

    private void txtCodigoEmpresaIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoEmpresaIDKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 114) //tecla F3 para pesquisa
        {
            btnPesquisaEmpresaIDActionPerformed(null);
        }
    }//GEN-LAST:event_txtCodigoEmpresaIDKeyPressed

    private void btnPesquisaParceiroIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaParceiroIDActionPerformed
        // TODO add your handling code here:
         variaveis.xColuna1 = "par_codigo_id";
         variaveis.xColuna2 = "par_nome_razao_social";
         variaveis.xColuna3 = "par_fantasia";
         variaveis.xColuna4 = "par_cnpj_cpf";
         variaveis.xColuna5 = "''";
         variaveis.xColuna6 = "''";
         variaveis.xColuna7 = "''";
         variaveis.xColuna8 = "''";
         variaveis.xColuna9 = "''";
         
         variaveis.xColunaNome1 = "Código";
         variaveis.xColunaNome2 = "Nome / Razão Social";
         variaveis.xColunaNome3 = "Fantasia";
         variaveis.xColunaNome4 = "CPF / CNPJ";
         variaveis.xColunaNome5 = "";
         variaveis.xColunaNome6 = "";
         variaveis.xColunaNome7 = "";
         variaveis.xColunaNome8 = "";
         variaveis.xColunaNome9 = "";
         
         variaveis.xColunaTamanho1 = 60;
         variaveis.xColunaTamanho2 = 450;
         variaveis.xColunaTamanho3 = 260;
         variaveis.xColunaTamanho4 = 120;
         variaveis.xColunaTamanho5 = 0;
         variaveis.xColunaTamanho6 = 0;
         variaveis.xColunaTamanho7 = 0;
         variaveis.xColunaTamanho8 = 0;
         variaveis.xColunaTamanho9 = 0;
         
         variaveis.xColunaStart = "par_nome_razao_social";
         variaveis.xColunaNomeStart = "Nome / Razão Social";
         variaveis.xTabela = "parceiros";
         variaveis.xSql = ""; 
         
         FpesqPesquisa md = new FpesqPesquisa(null, true);
         Dimension d = new Dimension();   
         d.setSize(900, 480); 
         md.setSize(d);
         
         md.setTitle("Pesquisa Parceiros - ENTER ou DUPLO CLICK no registro retorna dados.");

         md.setLocationRelativeTo(null);
         md.setVisible(true);

        if(!md.getRetorno().trim().equals("") ||!md.getRetorno().equals(null))
        {
          txtCodigoParceiroID.setText((String) md.getRetorno());
        }
        txtCodigoParceiroID.requestFocus();
        if (!txtCodigoParceiroID.getText().equals("")) {
            String vmCampos = "*";
            String vmCondicao_Consulta = " WHERE par_codigo_id = " + txtCodigoParceiroID.getText();
            try {
                rs = AcessoDados.Selecao("parceiros", vmCampos, vmCondicao_Consulta);
                rs.next();
                txtParceiro.setText(rs.getString("par_nome_razao_social"));
                txtCodigoParceiroID.requestFocus();
                rs.close();
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_btnPesquisaParceiroIDActionPerformed

    private void txtCodigoParceiroIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoParceiroIDKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 114) //tecla F3 para pesquisa
        {
            btnPesquisaParceiroIDActionPerformed(null);
        }
    }//GEN-LAST:event_txtCodigoParceiroIDKeyPressed

    private void btnPesquisaFormaPagamentoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaFormaPagamentoIDActionPerformed
        // TODO add your handling code here:
         variaveis.xColuna1 = "fpgto_codigo_id";
         variaveis.xColuna2 = "fpgto_descricao";
         variaveis.xColuna3 = "''";
         variaveis.xColuna4 = "''";
         variaveis.xColuna5 = "''";
         variaveis.xColuna6 = "''";
         variaveis.xColuna7 = "''";
         variaveis.xColuna8 = "''";
         variaveis.xColuna9 = "''";
         
         variaveis.xColunaNome1 = "Código";
         variaveis.xColunaNome2 = "Descrição";
         variaveis.xColunaNome3 = "";
         variaveis.xColunaNome4 = "";
         variaveis.xColunaNome5 = "";
         variaveis.xColunaNome6 = "";
         variaveis.xColunaNome7 = "";
         variaveis.xColunaNome8 = "";
         variaveis.xColunaNome9 = "";
         
         variaveis.xColunaTamanho1 = 60;
         variaveis.xColunaTamanho2 = 400;
         variaveis.xColunaTamanho3 = 0;
         variaveis.xColunaTamanho4 = 0;
         variaveis.xColunaTamanho5 = 0;
         variaveis.xColunaTamanho6 = 0;
         variaveis.xColunaTamanho7 = 0;
         variaveis.xColunaTamanho8 = 0;
         variaveis.xColunaTamanho9 = 0;
         
         variaveis.xColunaStart = "fpgto_descricao";
         variaveis.xColunaNomeStart = "Descrição";
         variaveis.xTabela = "forma_de_pagamento";
         variaveis.xSql = ""; 
         
         FpesqPesquisa md = new FpesqPesquisa(null, true);
         Dimension d = new Dimension();   
         d.setSize(470, 480); 
         md.setSize(d);
         
         md.setTitle("Pesquisa Forma de Pgto - ENTER ou DUPLO CLICK no registro retorna dados.");

         md.setLocationRelativeTo(null);
         md.setVisible(true);

        if(!md.getRetorno().trim().equals("") ||!md.getRetorno().equals(null))
        {
          txtFormaDePagamentoID.setText((String) md.getRetorno());
        }
        txtFormaDePagamentoID.requestFocus();
        if (!txtFormaDePagamentoID.getText().equals("")) {
            String vmCampos = "*";
            String vmCondicao_Consulta = " WHERE fpgto_codigo_id = " + txtFormaDePagamentoID.getText();
            try {
                rs = AcessoDados.Selecao("forma_de_pagamento", vmCampos, vmCondicao_Consulta);
                rs.next();
                txtFormaDePagamentoDescricao.setText(rs.getString("fpgto_descricao"));
                txtFormaDePagamentoID.requestFocus();
                rs.close();
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_btnPesquisaFormaPagamentoIDActionPerformed

    private void txtFormaDePagamentoIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFormaDePagamentoIDKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 114) //tecla F3 para pesquisa
        {
            btnPesquisaFormaPagamentoIDActionPerformed(null);
        }
    }//GEN-LAST:event_txtFormaDePagamentoIDKeyPressed

    private void btnPesquisaTipoDocumentoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaTipoDocumentoIDActionPerformed
        // TODO add your handling code here:
         variaveis.xColuna1 = "doc_codigo_id";
         variaveis.xColuna2 = "doc_descricao";
         variaveis.xColuna3 = "''";
         variaveis.xColuna4 = "''";
         variaveis.xColuna5 = "''";
         variaveis.xColuna6 = "''";
         variaveis.xColuna7 = "''";
         variaveis.xColuna8 = "''";
         variaveis.xColuna9 = "''";
         
         variaveis.xColunaNome1 = "Código";
         variaveis.xColunaNome2 = "Descrição";
         variaveis.xColunaNome3 = "";
         variaveis.xColunaNome4 = "";
         variaveis.xColunaNome5 = "";
         variaveis.xColunaNome6 = "";
         variaveis.xColunaNome7 = "";
         variaveis.xColunaNome8 = "";
         variaveis.xColunaNome9 = "";
         
         variaveis.xColunaTamanho1 = 60;
         variaveis.xColunaTamanho2 = 400;
         variaveis.xColunaTamanho3 = 0;
         variaveis.xColunaTamanho4 = 0;
         variaveis.xColunaTamanho5 = 0;
         variaveis.xColunaTamanho6 = 0;
         variaveis.xColunaTamanho7 = 0;
         variaveis.xColunaTamanho8 = 0;
         variaveis.xColunaTamanho9 = 0;
         
         variaveis.xColunaStart = "doc_descricao";
         variaveis.xColunaNomeStart = "Descrição";
         variaveis.xTabela = "tipo_documento";
         variaveis.xSql = ""; 
         
         FpesqPesquisa md = new FpesqPesquisa(null, true);
         Dimension d = new Dimension();   
         d.setSize(470, 480); 
         md.setSize(d);
         
         md.setTitle("Pesquisa Tipo Documento - ENTER ou DUPLO CLICK no registro retorna dados.");

         md.setLocationRelativeTo(null);
         md.setVisible(true);
       
        if(!md.getRetorno().trim().equals("") ||!md.getRetorno().equals(null))
        {
          txtTipoDeDocumentoID.setText((String) md.getRetorno());
        }
        txtTipoDeDocumentoID.requestFocus();
        if (!txtTipoDeDocumentoID.getText().equals("")) {
            String vmCampos = "*";
            String vmCondicao_Consulta = " WHERE doc_codigo_id = " + txtTipoDeDocumentoID.getText();
            try {
                rs = AcessoDados.Selecao("Tipo_documento", vmCampos, vmCondicao_Consulta);
                rs.next();
                txtTipoDeDocumentoDescricao.setText(rs.getString("doc_descricao"));
                txtTipoDeDocumentoID.requestFocus();
                rs.close();
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_btnPesquisaTipoDocumentoIDActionPerformed

    private void txtTipoDeDocumentoIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTipoDeDocumentoIDKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 114) //tecla F3 para pesquisa
        {
            btnPesquisaTipoDocumentoIDActionPerformed(null);
        }
    }//GEN-LAST:event_txtTipoDeDocumentoIDKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnPesquisaBancoIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnPesquisaBancoIDFocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnPesquisaBancoIDFocusLost

    private void txtBancoIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBancoIDKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == 114) //tecla F3 para pesquisa
        {
            btnPesquisaBancoIDActionPerformed(null);
        }
    }//GEN-LAST:event_txtBancoIDKeyPressed

    private void txtBancoIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBancoIDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBancoIDKeyReleased

    private void txtBancoIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBancoIDFocusLost
        // TODO add your handling code here:
        if (!txtBancoID.getText().equals("")) {
            String vmCampos = "*";
            String vmCondicao_Consulta = " WHERE banc_codigo_id = " + txtBancoID.getText();
            try {
                rs = AcessoDados.Selecao("Contas_bancarias", vmCampos, vmCondicao_Consulta);
                if (!rs.next()) {
                    JOptionPane.showMessageDialog(null, "Banco não cadastrado no sistema");
                    txtBancoID.setText(null);
                    txtBancoDescricao.setText(null);
                    txtBancoID.requestFocus();
                    return;
                }
                txtBancoDescricao.setText(rs.getString("banc_nome_banco"));
                rs.close();
            } catch (Exception e) {
                e.printStackTrace();
            }

        } else {
            txtBancoDescricao.setText(null);
        }
    }//GEN-LAST:event_txtBancoIDFocusLost

    private void btnPesquisaBancoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaBancoIDActionPerformed
        // TODO add your handling code here:
         variaveis.xColuna1 = "banc_codigo_id";
         variaveis.xColuna2 = "banc_nome_banco";
         variaveis.xColuna3 = "banc_numero_agencia";
         variaveis.xColuna4 = "banc_numero_conta";
         variaveis.xColuna5 = "''";
         variaveis.xColuna6 = "''";
         variaveis.xColuna7 = "''";
         variaveis.xColuna8 = "''";
         variaveis.xColuna9 = "''";
         
         variaveis.xColunaNome1 = "Código";
         variaveis.xColunaNome2 = "Descrição";
         variaveis.xColunaNome3 = "Agência";
         variaveis.xColunaNome4 = "C/C";
         variaveis.xColunaNome5 = "";
         variaveis.xColunaNome6 = "";
         variaveis.xColunaNome7 = "";
         variaveis.xColunaNome8 = "";
         variaveis.xColunaNome9 = "";
         
         variaveis.xColunaTamanho1 = 60;
         variaveis.xColunaTamanho2 = 250;
         variaveis.xColunaTamanho3 = 75;
         variaveis.xColunaTamanho4 = 75;
         variaveis.xColunaTamanho5 = 0;
         variaveis.xColunaTamanho6 = 0;
         variaveis.xColunaTamanho7 = 0;
         variaveis.xColunaTamanho8 = 0;
         variaveis.xColunaTamanho9 = 0;
         
         variaveis.xColunaStart = "banc_nome_banco";
         variaveis.xColunaNomeStart = "Descrição";
         variaveis.xTabela = "contas_bancarias";
         variaveis.xSql = ""; 
         
         FpesqPesquisa md = new FpesqPesquisa(null, true);
         Dimension d = new Dimension();   
         d.setSize(470, 480); 
         md.setSize(d);
         
         md.setTitle("Pesquisa Conta Bancária - ENTER ou DUPLO CLICK no registro retorna dados.");

         md.setLocationRelativeTo(null);
         md.setVisible(true);

        if(!md.getRetorno().trim().equals("") ||!md.getRetorno().equals(null))
        {
        txtBancoID.setText((String) md.getRetorno());
        }
        txtBancoID.requestFocus();
        if (!txtBancoID.getText().equals("")) {
            String vmCampos = "*";
            String vmCondicao_Consulta = " WHERE banc_codigo_id = " + txtBancoID.getText();
            try {
                rs = AcessoDados.Selecao("Contas_bancarias", vmCampos, vmCondicao_Consulta);
                rs.next();
                txtBancoDescricao.setText(rs.getString("banc_nome_banco"));
                rs.close();
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_btnPesquisaBancoIDActionPerformed

    private void txtVencimentoFimFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVencimentoFimFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVencimentoFimFocusLost

    private void txtVencimentoIniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVencimentoIniFocusLost
        // TODO add your handling code here:

        if (!txtVencimentoIni.getText().equals("  /  /    "))
        {
           try
           {
               SimpleDateFormat formatIso = new SimpleDateFormat("dd/MM/yyyy");
               Date dat =  formatIso.parse(txtVencimentoIni.getText());
           }
           catch (Exception e)
           {
             JOptionPane.showMessageDialog(null,"Data Inválida");
             txtVencimentoIni.setText("");
             txtVencimentoIni.requestFocus();
             return;
           }
        }

    }//GEN-LAST:event_txtVencimentoIniFocusLost

    private void txtCodigoEmpresaIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoEmpresaIDFocusGained
        // TODO add your handling code here:
        JTextField tf = (JTextField) evt.getComponent();
        tf.selectAll();
    }//GEN-LAST:event_txtCodigoEmpresaIDFocusGained

    private void txtCodigoParceiroIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoParceiroIDFocusGained
        // TODO add your handling code here:
        JTextField tf = (JTextField) evt.getComponent();
        tf.selectAll();
    }//GEN-LAST:event_txtCodigoParceiroIDFocusGained

    private void txtVencimentoIniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVencimentoIniFocusGained
        // TODO add your handling code here:
        JTextField tf = (JTextField) evt.getComponent();
        tf.selectAll();

    }//GEN-LAST:event_txtVencimentoIniFocusGained

    private void txtVencimentoFimFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVencimentoFimFocusGained
        // TODO add your handling code here:
        JTextField tf = (JTextField) evt.getComponent();
        tf.selectAll();

    }//GEN-LAST:event_txtVencimentoFimFocusGained

    private void txtFormaDePagamentoIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFormaDePagamentoIDFocusGained
        // TODO add your handling code here:
        JTextField tf = (JTextField) evt.getComponent();
        tf.selectAll();

    }//GEN-LAST:event_txtFormaDePagamentoIDFocusGained

    private void txtTipoDeDocumentoIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTipoDeDocumentoIDFocusGained
        // TODO add your handling code here:
        JTextField tf = (JTextField) evt.getComponent();
        tf.selectAll();

    }//GEN-LAST:event_txtTipoDeDocumentoIDFocusGained

    private void txtBancoIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBancoIDFocusGained
        // TODO add your handling code here:
        JTextField tf = (JTextField) evt.getComponent();
        tf.selectAll();

    }//GEN-LAST:event_txtBancoIDFocusGained


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                RelContasReceber dialog = new RelContasReceber(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnPesquisaBancoID;
    private javax.swing.JButton btnPesquisaEmpresaID;
    private javax.swing.JButton btnPesquisaFormaPagamentoID;
    private javax.swing.JButton btnPesquisaParceiroID;
    private javax.swing.JButton btnPesquisaTipoDocumentoID;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox cbPosicao;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField txtBancoDescricao;
    private javax.swing.JTextField txtBancoID;
    private javax.swing.JTextField txtCodigoEmpresaID;
    private javax.swing.JTextField txtCodigoParceiroID;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtFormaDePagamentoDescricao;
    private javax.swing.JTextField txtFormaDePagamentoID;
    private javax.swing.JTextField txtParceiro;
    private javax.swing.JTextField txtTipoDeDocumentoDescricao;
    private javax.swing.JTextField txtTipoDeDocumentoID;
    private javax.swing.JFormattedTextField txtVencimentoFim;
    private javax.swing.JFormattedTextField txtVencimentoIni;
    // End of variables declaration//GEN-END:variables
}
