/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmContasPagar.java
 *
 * Created on 06/02/2010, 14:19:37
 */
package Relatorios;

import sae.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.*;
import Classes.claAcessoDados;
import Classes.claVariaveis;
import Classes.claFuncoes;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import Classes.claVariaveis;
import Classes.claAcessoDados;
import it.businesslogic.ireport.chart.ChartFactory;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.text.html.parser.Parser;

import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.*;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.StandardCategoryItemLabelGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.CategoryItemRenderer;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;


/**
 *
 * @author Thiago
 */
public class RelGraficoVendas extends javax.swing.JDialog {

    claVariaveis variaveis = new claVariaveis();
    claAcessoDados AcessoDados = new claAcessoDados();
    claFuncoes funcoes = new claFuncoes();
    private ResultSet rs;

    /** Creates new form FrmContasPagar */
    public RelGraficoVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        funcoes.F_AtribuirClasse(rootPane);
        btnImprimir.setFocusTraversalKeysEnabled(false);
        txtCodigoEmpresaID.requestFocus();

    }
    public static int vm_ID;


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        btnImprimir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        txtEmpresa = new javax.swing.JTextField();
        btnPesquisaEmpresaID = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoEmpresaID = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtVencimentoIni = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        txtVencimentoFim = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        txtCodVendedor = new javax.swing.JTextField();
        btnPesquisaVendedor = new javax.swing.JButton();
        txtVendedor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gráfico Demonstrativo de Vendas / Vendedor");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imprimir.gif"))); // NOI18N
        btnImprimir.setToolTipText("Imprimir");
        btnImprimir.setBorderPainted(false);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sair.gif"))); // NOI18N
        btnSair.setBorderPainted(false);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE)
            .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        txtEmpresa.setEditable(false);
        txtEmpresa.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtEmpresa.setForeground(new java.awt.Color(102, 102, 255));
        txtEmpresa.setFocusable(false);
        txtEmpresa.setRequestFocusEnabled(false);

        btnPesquisaEmpresaID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.gif"))); // NOI18N
        btnPesquisaEmpresaID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPesquisaEmpresaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaEmpresaIDActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel2.setText("Empresa :");

        txtCodigoEmpresaID.setColumns(8);
        txtCodigoEmpresaID.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtCodigoEmpresaID.setToolTipText("Código");
        txtCodigoEmpresaID.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtCodigoEmpresaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoEmpresaIDActionPerformed(evt);
            }
        });
        txtCodigoEmpresaID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoEmpresaIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoEmpresaIDFocusLost(evt);
            }
        });
        txtCodigoEmpresaID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoEmpresaIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoEmpresaIDKeyReleased(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ano", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel7.setText("Inicial:");

        txtVencimentoIni.setColumns(4);
        try {
            txtVencimentoIni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtVencimentoIni.setToolTipText("Número");
        txtVencimentoIni.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtVencimentoIni.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtVencimentoIni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVencimentoIniFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVencimentoIniFocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel9.setText("Final:");

        txtVencimentoFim.setColumns(4);
        try {
            txtVencimentoFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtVencimentoFim.setToolTipText("Número");
        txtVencimentoFim.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtVencimentoFim.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtVencimentoFim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVencimentoFimFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVencimentoFimFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtVencimentoIni, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(24, 24, 24)
                .addComponent(txtVencimentoFim, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtVencimentoIni, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtVencimentoFim, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel16.setText("Vendedor:");
        jLabel16.setToolTipText("");

        txtCodVendedor.setColumns(8);
        txtCodVendedor.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtCodVendedor.setToolTipText("Código");
        txtCodVendedor.setName("ped_func_codigo_id"); // NOI18N
        txtCodVendedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodVendedorFocusLost(evt);
            }
        });
        txtCodVendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodVendedorKeyPressed(evt);
            }
        });

        btnPesquisaVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.gif"))); // NOI18N
        btnPesquisaVendedor.setToolTipText("");
        btnPesquisaVendedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPesquisaVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaVendedorActionPerformed(evt);
            }
        });

        txtVendedor.setEditable(false);
        txtVendedor.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtVendedor.setForeground(new java.awt.Color(102, 102, 255));
        txtVendedor.setToolTipText("");
        txtVendedor.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtVendedor.setFocusable(false);
        txtVendedor.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtCodigoEmpresaID, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPesquisaVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPesquisaEmpresaID, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVendedor)
                            .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisaEmpresaID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoEmpresaID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel16))
                    .addComponent(txtCodVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisaVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtCodigoEmpresaIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoEmpresaIDFocusLost
        // TODO add your handling code here:
        // if (txtCodigoEmpresaID.getText().equals(null) || (txtCodigoEmpresaID.getText().equals("")))
        //    {
        //        txtCodigoEmpresaID.setText("1");

        //    }
        if (!txtCodigoEmpresaID.getText().equals("")) {
            String vmCampos = "*";
            String vmCondicao_Consulta = " WHERE emp_codigo_id = " + txtCodigoEmpresaID.getText();
            try {
                rs = AcessoDados.Selecao("empresas", vmCampos, vmCondicao_Consulta);
                if (!rs.next()) {
                    JOptionPane.showMessageDialog(null, "Empresa não cadastrada no sistema");
                    txtCodigoEmpresaID.setText(null);
                    txtEmpresa.setText(null);
                    txtEmpresa.requestFocus();
                    return;
                }
                txtEmpresa.setText(rs.getString("emp_nome"));
                rs.close();
            } catch (Exception e) {
                e.printStackTrace();
            }

        } else {
            txtEmpresa.setText(null);
        }
    }//GEN-LAST:event_txtCodigoEmpresaIDFocusLost

    private void txtCodigoEmpresaIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoEmpresaIDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoEmpresaIDKeyReleased

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        //String xDataCP = "CP_DATA_EMISSAO";
        String xDataCR = "CR_DATA_EMISSAO";
        if (txtEmpresa.getText().equals(null) || (txtEmpresa.getText().equals("")))
        {
           JOptionPane.showMessageDialog(null,"Favor informar a Empresa.");
           txtCodigoEmpresaID.requestFocus();
           return;
        }

      
        if (txtVencimentoIni.getText().equals("") || (txtVencimentoFim.getText().equals("")))
        {
           JOptionPane.showMessageDialog(null,"Período de vencimento inválido.");
           txtVencimentoIni.requestFocus();
           return;
        }
    
      String vmCondicao_Consulta = " SELECT extract(month FROM "+xDataCR+") AS MES, "+
      " extract(YEAR FROM "+xDataCR+") AS ANO,"+
      " SUM(CR_VALOR_DOCUMENTO) AS VALOR,"+
      " TRIM(TO_CHAR(SUM(CR_VALOR_DOCUMENTO), '9G999G999D99')) AS VALOR_TEXTO,"+
      "  CASE WHEN extract(month FROM "+xDataCR+") = 1 THEN 'JAN-' || extract(YEAR FROM "+xDataCR+")"+
      "       WHEN extract(month FROM "+xDataCR+") = 2 THEN 'FEV-' || extract(YEAR FROM "+xDataCR+")"+
      "       WHEN extract(month FROM "+xDataCR+") = 3 THEN 'MAR-' || extract(YEAR FROM "+xDataCR+")"+
      "       WHEN extract(month FROM "+xDataCR+") = 4 THEN 'ABR-' || extract(YEAR FROM "+xDataCR+")"+
      "       WHEN extract(month FROM "+xDataCR+") = 5 THEN 'MAI-' || extract(YEAR FROM "+xDataCR+")"+
      "       WHEN extract(month FROM "+xDataCR+") = 6 THEN 'JUN-' || extract(YEAR FROM "+xDataCR+")"+
      "       WHEN extract(month FROM "+xDataCR+") = 7 THEN 'JUL-' || extract(YEAR FROM "+xDataCR+")"+
      "       WHEN extract(month FROM "+xDataCR+") = 8 THEN 'AGO-' || extract(YEAR FROM "+xDataCR+")"+
      "       WHEN extract(month FROM "+xDataCR+") = 9 THEN 'SET-' || extract(YEAR FROM "+xDataCR+")"+
      "       WHEN extract(month FROM "+xDataCR+") = 10 THEN 'OUT-' || extract(YEAR FROM "+xDataCR+")"+
      "       WHEN extract(month FROM "+xDataCR+") = 11 THEN 'NOV-' || extract(YEAR FROM "+xDataCR+")"+
      "       WHEN extract(month FROM "+xDataCR+") = 12 THEN 'DEZ-' || extract(YEAR FROM "+xDataCR+") END  AS MESEX,"+
      "       FUNC_NOME, "+
      "(SELECT SUM(CR_VALOR_DOCUMENTO) FROM CONTAS_RECEBER " + 
      "  INNER JOIN PEDIDOS ON (ped_numero_nota_fiscal = cr_nota_fiscal) " +
      "  INNER JOIN FUNCIONARIOS ON (PED_FUNC_CODIGO_ID = FUNC_CODIGO_ID)" +
      " WHERE  (extract(YEAR FROM "+xDataCR+") >= "+txtVencimentoIni.getText()+ ") and (extract(YEAR FROM "+xDataCR+") <= "+txtVencimentoFim.getText()+ ")";
      if(txtCodVendedor.getText().length() > 0)
      {
          vmCondicao_Consulta += " AND FUNC_CODIGO_ID = "+ txtCodVendedor.getText();
      }
              
        vmCondicao_Consulta += ") AS VENDAS  " +
              
      " FROM CONTAS_RECEBER"+

      "  INNER JOIN PEDIDOS ON (ped_numero_nota_fiscal = cr_nota_fiscal) "+  
      "  INNER JOIN FUNCIONARIOS ON (PED_FUNC_CODIGO_ID = FUNC_CODIGO_ID) "+

      " WHERE  (extract(YEAR FROM "+xDataCR+") >= "+txtVencimentoIni.getText()+ ") and (extract(YEAR FROM "+xDataCR+") <= "+txtVencimentoFim.getText()+ ")"+ 
      //" AND    (extract(month FROM "+xDataCR+") >= "+xMesIni+ ") and (extract(month FROM "+xDataCR+") <= "+xMesFim+ ")"+
      " AND    (CR_EMP_CODIGO_ID = " + txtCodigoEmpresaID.getText() + ")";
      if(txtCodVendedor.getText().length() > 0)
      {
          vmCondicao_Consulta += " AND FUNC_CODIGO_ID = "+ txtCodVendedor.getText();
      }
    
      
      vmCondicao_Consulta += " GROUP BY extract(month FROM "+xDataCR+"),"+
      "      extract(YEAR FROM "+xDataCR+"), FUNC_NOME "+
      " order by 2, 1";

      try
        {
        rs = AcessoDados.SelecaoUNION(vmCondicao_Consulta);
         }catch (Exception e) {
           e.printStackTrace();
        }

      
        HashMap map = new HashMap();

        try
        {
        
        map.put("Pempresa",   "EMPRESA  : " + txtEmpresa.getText());
        String caminho = getClass().getResource("/Imagens/Logo.jpg").toString();
        map.put("pLogo", caminho);

       
        JasperReport jr = (JasperReport) JRLoader.loadObject(getClass().getClassLoader().getResource("Relatorios/GraVendas.jasper"));
        JRResultSetDataSource jrRS1 = new JRResultSetDataSource(rs);
        //JasperReport jr = (JasperReport) JRLoader.loadObject(arquivo);

        JasperPrint jp = JasperFillManager.fillReport(jr, map,jrRS1);
        
        JasperViewer jv = new JasperViewer(jp,false);
        JDialog viewer = new  JDialog(jv, true);
        
        viewer.setSize(1000,720);
        viewer.setLocationRelativeTo(null);
        viewer.getContentPane().add(jv.getContentPane());
        viewer.setVisible(true);

          }catch (Exception e) {
           e.printStackTrace();
        }

        txtEmpresa.requestFocus();


    }//GEN-LAST:event_btnImprimirActionPerformed
public class CustomizerLabelExpression implements JRChartCustomizer {   
  
    public void customize(JFreeChart chart, JRChart jasperChart){   
           
        CategoryPlot plot = (CategoryPlot)chart.getPlot();   
  
        CategoryItemRenderer line = plot.getRenderer();   
//         
        //aqui é definido o label   
        line.setBaseItemLabelGenerator(new StandardCategoryItemLabelGenerator());   
        line.setBaseItemLabelsVisible(true);   
        line.setBaseItemLabelPaint(Color.BLACK);   
  
    }   
}  

    private void btnPesquisaEmpresaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaEmpresaIDActionPerformed
        // TODO add your handling code here:
         variaveis.xColuna1 = "emp_codigo_id";
         variaveis.xColuna2 = "emp_nome";
         variaveis.xColuna3 = "emp_nome_fantasia";
         variaveis.xColuna4 = "emp_cnpj";
         variaveis.xColuna5 = "''";
         variaveis.xColuna6 = "''";
         variaveis.xColuna7 = "''";
         variaveis.xColuna8 = "''";
         variaveis.xColuna9 = "''";
         
         variaveis.xColunaNome1 = "Código";
         variaveis.xColunaNome2 = "Razão Social";
         variaveis.xColunaNome3 = "Fantasia";
         variaveis.xColunaNome4 = "CPF / CNPJ";
         variaveis.xColunaNome5 = "";
         variaveis.xColunaNome6 = "";
         variaveis.xColunaNome7 = "";
         variaveis.xColunaNome8 = "";
         variaveis.xColunaNome9 = "";
         
         variaveis.xColunaTamanho1 = 60;
         variaveis.xColunaTamanho2 = 450;
         variaveis.xColunaTamanho3 = 260;
         variaveis.xColunaTamanho4 = 120;
         variaveis.xColunaTamanho5 = 0;
         variaveis.xColunaTamanho6 = 0;
         variaveis.xColunaTamanho7 = 0;
         variaveis.xColunaTamanho8 = 0;
         variaveis.xColunaTamanho9 = 0;
         
         variaveis.xColunaStart = "emp_nome";
         variaveis.xColunaNomeStart = "Razão Social";
         variaveis.xTabela = "empresas";
         variaveis.xSql = ""; 
         
         FpesqPesquisa md = new FpesqPesquisa(null, true);
         Dimension d = new Dimension();   
         d.setSize(900, 480); 
         md.setSize(d);
         
         md.setTitle("Pesquisa Empresa - ENTER ou DUPLO CLICK no registro retorna dados.");

         md.setLocationRelativeTo(null);
         md.setVisible(true);

        if(!md.getRetorno().trim().equals("") ||!md.getRetorno().equals(null))
        {
          txtCodigoEmpresaID.setText((String) md.getRetorno());
        }

        txtCodigoEmpresaID.requestFocus();
        if (!txtCodigoEmpresaID.getText().equals("")) {
            String vmCampos = "*";
            String vmCondicao_Consulta = " WHERE emp_codigo_id = " + txtCodigoEmpresaID.getText();
            try {
                rs = AcessoDados.Selecao("empresas", vmCampos, vmCondicao_Consulta);
                rs.next();
                txtEmpresa.setText(rs.getString("emp_nome"));
                txtCodigoEmpresaID.requestFocus();
                rs.close();
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_btnPesquisaEmpresaIDActionPerformed

    private void txtCodigoEmpresaIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoEmpresaIDKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 114) //tecla F3 para pesquisa
        {
            btnPesquisaEmpresaIDActionPerformed(null);
        }
    }//GEN-LAST:event_txtCodigoEmpresaIDKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void txtVencimentoFimFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVencimentoFimFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVencimentoFimFocusLost

    private void txtVencimentoIniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVencimentoIniFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_txtVencimentoIniFocusLost

    private void txtCodigoEmpresaIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoEmpresaIDFocusGained
        // TODO add your handling code here:
        JTextField tf = (JTextField) evt.getComponent();
        tf.selectAll();
    }//GEN-LAST:event_txtCodigoEmpresaIDFocusGained

    private void txtVencimentoIniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVencimentoIniFocusGained
        // TODO add your handling code here:
        JTextField tf = (JTextField) evt.getComponent();
        tf.selectAll();

    }//GEN-LAST:event_txtVencimentoIniFocusGained

    private void txtVencimentoFimFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVencimentoFimFocusGained
        // TODO add your handling code here:
        JTextField tf = (JTextField) evt.getComponent();
        tf.selectAll();

    }//GEN-LAST:event_txtVencimentoFimFocusGained

    private void txtCodigoEmpresaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoEmpresaIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoEmpresaIDActionPerformed

    private void txtCodVendedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodVendedorFocusLost
        // TODO add your handling code here:
        if (!txtCodVendedor.getText().equals("")) {
            String vmCampos = "*";
            String vmCondicao_Consulta = " WHERE func_codigo_id = " + txtCodVendedor.getText();
            try {
                rs = AcessoDados.Selecao("funcionarios", vmCampos, vmCondicao_Consulta);
                if (!rs.next()) {
                    JOptionPane.showMessageDialog(null, "Vendedor não cadastrado no sistema");
                    txtCodVendedor.setText(null);
                    txtVendedor.setText(null);
                    txtCodVendedor.requestFocus();
                    return;
                }
                txtVendedor.setText(rs.getString("func_nome"));
                rs.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            txtVendedor.setText("");
        }

    }//GEN-LAST:event_txtCodVendedorFocusLost

    private void txtCodVendedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodVendedorKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 114) //tecla F3 para pesquisa
        {
            btnPesquisaVendedorActionPerformed(null);
        }

    }//GEN-LAST:event_txtCodVendedorKeyPressed

    private void btnPesquisaVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaVendedorActionPerformed
        // TODO add your handling code here:
        variaveis.xColuna1 = "func_codigo_id";
        variaveis.xColuna2 = "func_nome";
        variaveis.xColuna3 = "func_cargo";
        variaveis.xColuna4 = "''";
        variaveis.xColuna5 = "''";
        variaveis.xColuna6 = "''";
        variaveis.xColuna7 = "''";
        variaveis.xColuna8 = "''";
        variaveis.xColuna9 = "''";

        variaveis.xColunaNome1 = "Código";
        variaveis.xColunaNome2 = "Nome";
        variaveis.xColunaNome3 = "Cargo";
        variaveis.xColunaNome4 = "";
        variaveis.xColunaNome5 = "";
        variaveis.xColunaNome6 = "";
        variaveis.xColunaNome7 = "";
        variaveis.xColunaNome8 = "";
        variaveis.xColunaNome9 = "";

        variaveis.xColunaTamanho1 = 60;
        variaveis.xColunaTamanho2 = 400;
        variaveis.xColunaTamanho3 = 190;
        variaveis.xColunaTamanho4 = 0;
        variaveis.xColunaTamanho5 = 0;
        variaveis.xColunaTamanho6 = 0;
        variaveis.xColunaTamanho7 = 0;
        variaveis.xColunaTamanho8 = 0;
        variaveis.xColunaTamanho9 = 0;

        variaveis.xColunaStart = "func_nome";
        variaveis.xColunaNomeStart = "Nome";
        variaveis.xTabela = "funcionarios";
        variaveis.xSql = "";

        FpesqPesquisa md = new FpesqPesquisa(null, true);
        Dimension d = new Dimension();
        d.setSize(660, 480);
        md.setSize(d);

        md.setTitle("Pesquisa Funcionário - ENTER ou DUPLO CLICK no registro retorna dados.");

        md.setLocationRelativeTo(null);
        md.setVisible(true);

        txtCodVendedor.setText(null);
        txtCodVendedor.setText((String) md.getRetorno());
        txtCodVendedor.requestFocus();
        if (!txtCodVendedor.getText().equals("")) {
            String vmCampos = "*";
            String vmCondicao_Consulta = " WHERE func_codigo_id = " + txtCodVendedor.getText();
            try {
                rs = AcessoDados.Selecao("funcionarios", vmCampos, vmCondicao_Consulta);
                rs.next();
                txtVendedor.setText(rs.getString("func_nome"));
                rs.close();
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_btnPesquisaVendedorActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                RelGraficoVendas dialog = new RelGraficoVendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnPesquisaEmpresaID;
    private javax.swing.JButton btnPesquisaVendedor;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField txtCodVendedor;
    private javax.swing.JTextField txtCodigoEmpresaID;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JFormattedTextField txtVencimentoFim;
    private javax.swing.JFormattedTextField txtVencimentoIni;
    private javax.swing.JTextField txtVendedor;
    // End of variables declaration//GEN-END:variables
}
