/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmContasPagar.java
 *
 * Created on 06/02/2010, 14:19:37
 */
package Relatorios;

import sae.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.*;
import Classes.claAcessoDados;
import Classes.claVariaveis;
import Classes.claFuncoes;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import Classes.claVariaveis;
import Classes.claAcessoDados;

import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.text.html.parser.Parser;

import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.*;

/**
 *
 * @author Thiago
 */
public class RelPedidoCliente extends javax.swing.JDialog {
    
    claVariaveis variaveis = new claVariaveis();
    claAcessoDados AcessoDados = new claAcessoDados();
    claFuncoes funcoes = new claFuncoes();
    private ResultSet rs;
    String vParceiro = "TODOS OS PARCEIROS";
    String vProduto = "TODOS OS PRODUTOS";
    String vmCampos = "";
    /** Creates new form FrmContasPagar */
    public RelPedidoCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        funcoes.F_AtribuirClasse(rootPane);
        btnImprimir.setFocusTraversalKeysEnabled(false);
        txtCodigoEmpresaID.requestFocus();
      

    }
    public static int vm_ID;


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        btnImprimir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        btnPesquisaEmpresaID = new javax.swing.JButton();
        txtParceiro = new javax.swing.JTextField();
        btnPesquisaParceiroID = new javax.swing.JButton();
        txtCodigoParceiroID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoEmpresaID = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtVencimentoIni = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        txtVencimentoFim = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        ddlTipoPedido = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relação de Pedidos / Clientes");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imprimir.gif"))); // NOI18N
        btnImprimir.setToolTipText("Salvar");
        btnImprimir.setBorderPainted(false);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sair.gif"))); // NOI18N
        btnSair.setBorderPainted(false);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE)
            .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel3.setText("Parceiro :");

        txtEmpresa.setEditable(false);
        txtEmpresa.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtEmpresa.setForeground(new java.awt.Color(102, 102, 255));
        txtEmpresa.setToolTipText("");
        txtEmpresa.setFocusable(false);
        txtEmpresa.setRequestFocusEnabled(false);

        btnPesquisaEmpresaID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.gif"))); // NOI18N
        btnPesquisaEmpresaID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPesquisaEmpresaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaEmpresaIDActionPerformed(evt);
            }
        });

        txtParceiro.setEditable(false);
        txtParceiro.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtParceiro.setForeground(new java.awt.Color(102, 102, 255));
        txtParceiro.setToolTipText("");
        txtParceiro.setFocusable(false);
        txtParceiro.setRequestFocusEnabled(false);

        btnPesquisaParceiroID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.gif"))); // NOI18N
        btnPesquisaParceiroID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPesquisaParceiroID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaParceiroIDActionPerformed(evt);
            }
        });

        txtCodigoParceiroID.setColumns(8);
        txtCodigoParceiroID.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtCodigoParceiroID.setToolTipText("Código");
        txtCodigoParceiroID.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtCodigoParceiroID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoParceiroIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoParceiroIDFocusLost(evt);
            }
        });
        txtCodigoParceiroID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoParceiroIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoParceiroIDKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel2.setText("Empresa :");

        txtCodigoEmpresaID.setColumns(8);
        txtCodigoEmpresaID.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtCodigoEmpresaID.setToolTipText("Código");
        txtCodigoEmpresaID.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtCodigoEmpresaID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoEmpresaIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoEmpresaIDFocusLost(evt);
            }
        });
        txtCodigoEmpresaID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoEmpresaIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoEmpresaIDKeyReleased(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Emissão", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10))); // NOI18N
        jPanel7.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel7.setText("Inicial :");

        try {
            txtVencimentoIni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtVencimentoIni.setToolTipText("");
        txtVencimentoIni.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtVencimentoIni.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtVencimentoIni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVencimentoIniFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVencimentoIniFocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel9.setText("Final :");

        try {
            txtVencimentoFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtVencimentoFim.setToolTipText("");
        txtVencimentoFim.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtVencimentoFim.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtVencimentoFim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVencimentoFimFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVencimentoFimFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(6, 6, 6)
                .addComponent(txtVencimentoIni, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(3, 3, 3)
                .addComponent(txtVencimentoFim, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtVencimentoIni, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtVencimentoFim, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de Movimento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10))); // NOI18N
        jPanel1.setToolTipText("");

        ddlTipoPedido.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        ddlTipoPedido.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TODOS", "V - Venda", "P - Pendente", "O - Orçamento", "D - Devolução", "B - Bonificação", "E - Entrada", "F - Faturado", "C - Cancelado" }));
        ddlTipoPedido.setToolTipText("");
        ddlTipoPedido.setName("ped_tipo_pedido"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ddlTipoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(381, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ddlTipoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigoParceiroID, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(txtCodigoEmpresaID, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPesquisaEmpresaID, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(btnPesquisaParceiroID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmpresa)
                            .addComponent(txtParceiro)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(btnPesquisaEmpresaID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoEmpresaID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCodigoParceiroID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addComponent(btnPesquisaParceiroID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(txtParceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtCodigoEmpresaIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoEmpresaIDFocusLost
        // TODO add your handling code here:
        // if (txtCodigoEmpresaID.getText().equals(null) || (txtCodigoEmpresaID.getText().equals("")))
        //    {
        //        txtCodigoEmpresaID.setText("1");

        //    }
        if (!txtCodigoEmpresaID.getText().equals("")) {
            String vmCampos = "*";
            String vmCondicao_Consulta = " WHERE emp_codigo_id = " + txtCodigoEmpresaID.getText();
            try {
                rs = AcessoDados.Selecao("empresas", vmCampos, vmCondicao_Consulta);
                if (!rs.next()) {
                    JOptionPane.showMessageDialog(null, "Empresa não cadastrada no sistema");
                    txtCodigoEmpresaID.setText(null);
                    txtEmpresa.setText(null);
                    txtEmpresa.requestFocus();
                    return;
                }
                txtEmpresa.setText(rs.getString("emp_nome"));
                txtCodigoParceiroID.requestFocus();
                rs.close();
            } catch (Exception e) {
                e.printStackTrace();
            }

        } else {
            txtEmpresa.setText(null);
        }
    }//GEN-LAST:event_txtCodigoEmpresaIDFocusLost

    private void txtCodigoParceiroIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoParceiroIDFocusLost
        // TODO add your handling code here:
        if (!txtCodigoParceiroID.getText().equals("")) {
            String vmCampos = "*";
            String vmCondicao_Consulta = " WHERE par_codigo_id = " + txtCodigoParceiroID.getText();
            try {
                rs = AcessoDados.Selecao("parceiros", vmCampos, vmCondicao_Consulta);
                if (!rs.next()) {
                    JOptionPane.showMessageDialog(null, "Parceiro não cadastrado no sistema");
                    txtCodigoParceiroID.setText(null);
                    txtParceiro.setText(null);
                    txtParceiro.requestFocus();
                    return;
                }
                txtParceiro.setText(rs.getString("par_nome_razao_social"));
                rs.close();
            } catch (Exception e) {
                e.printStackTrace();
            }

        } else {
            txtParceiro.setText(null);
        }
    }//GEN-LAST:event_txtCodigoParceiroIDFocusLost

    private void txtCodigoEmpresaIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoEmpresaIDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoEmpresaIDKeyReleased

    private void txtCodigoParceiroIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoParceiroIDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoParceiroIDKeyReleased

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        if (txtEmpresa.getText().equals(null) || (txtEmpresa.getText().equals("")))
        {
           JOptionPane.showMessageDialog(null,"Favor informar a Empresa.");
           txtCodigoEmpresaID.requestFocus();
           return;
        }


          if (txtVencimentoIni.getText().equals("  /  /    ") || (txtVencimentoFim.getText().equals("  /  /    ")))
          {
             JOptionPane.showMessageDialog(null,"Período inválido.");
             txtVencimentoIni.requestFocus();
             return;
          }

        try
        {
           String vmCampos = " PED.*, PAR.*, ITEM.*, PROD.*, UNID.* "; 
           String vmParamentro = " INNER JOIN PARCEIROS PAR ON (PAR_CODIGO_ID = PED_PAR_CODIGO_ID)" +
                                 " INNER JOIN ITEM_PEDIDO ITEM ON (ITEM.item_ped_pedido_codigo_id = PED.ped_codigo_id) " +
                                 " INNER JOIN PRODUTOS PROD ON (PROD.PROD_CODIGO_ID = ITEM.item_ped_prod_codigo_id) " +
                                 " INNER JOIN UNIDADE_DE_MEDIDA UNID ON (UNID.unid_codigo_id = PROD.PROD_CODIGO_ID) "+
                                 " where PED.PED_DATA_EMISSAO >= '" + txtVencimentoIni.getText() +"' AND PED.PED_DATA_EMISSAO <= '" + txtVencimentoFim.getText() + "'";
         
           if(ddlTipoPedido.getSelectedIndex() != 0)
           {
               vmParamentro += " AND PED.PED_TIPO_PEDIDO = '" + ddlTipoPedido.getSelectedItem().toString() +"' ";
           }
           if(txtCodigoParceiroID.getText().length() > 0 )
           {
               vmParamentro += " AND PAR.PAR_CODIGO_ID = " + txtCodigoParceiroID.getText();
           }
           
           vmParamentro +=       " order by par.par_nome_razao_social, ped.ped_data_emissao desc , ped.ped_codigo_id ";
           
            
        rs = AcessoDados.Selecao("PEDIDOS PED", vmCampos, vmParamentro);
         }catch (Exception e) {
           JOptionPane.showMessageDialog(null,e.toString());
        }

        HashMap map = new HashMap();

        try
        {
        map.put("pEmpresa",   "EMPRESA  : " + txtEmpresa.getText());
        map.put("pVencimento","PERIODO   : " + txtVencimentoIni.getText() + " a " + txtVencimentoFim.getText());
        String caminho = getClass().getResource("/Imagens/Logo.jpg").toString();
        map.put("pLogo", caminho);


        JasperReport jr = (JasperReport) JRLoader.loadObject(getClass().getClassLoader().getResource("Relatorios/RelPedidoCliente.jasper"));
        JRResultSetDataSource jrRS1 = new JRResultSetDataSource(rs);
        //JasperReport jr = (JasperReport) JRLoader.loadObject(arquivo);

        JasperPrint jp = JasperFillManager.fillReport(jr, map,jrRS1);
        JasperViewer jv = new JasperViewer(jp,false);
        JDialog viewer = new  JDialog(jv, true);
        viewer.setSize(1000,700);
        viewer.setLocationRelativeTo(null);
        viewer.getContentPane().add(jv.getContentPane());
        viewer.setVisible(true);

          }catch (Exception e) {
           JOptionPane.showMessageDialog(null,e.getMessage());
        }

        txtEmpresa.requestFocus();


    }//GEN-LAST:event_btnImprimirActionPerformed

    public void RelatorioAnalitico()
    {
        vmCampos = "";

        vmCampos += " SELECT ";
        vmCampos += " ent_data as Data1,";
        vmCampos += " ent_controle_interno as controle,";
        vmCampos += " prod_codigo_produto as codigo,";
        vmCampos += " prod_descricao as descricao,";
        vmCampos += " sum(item_quantidade) as total,";
        vmCampos += " 'ENTRADA' as Tipo,";
        vmCampos += " sum(item_quantidade)as qtde";

        vmCampos += " FROM ENTRADA_INTERNA";
        vmCampos += " LEFT JOIN item_entrada_interna ON (item_ent_codigo_id = ent_codigo_id)";
        vmCampos += " LEFT JOIN PRODUTOS ON (PROD_CODIGO_ID = ITEM_PROD_CODIGO_ID)";

        vmCampos += " WHERE ENT_EMP_CODIGO_ID = " + txtCodigoEmpresaID.getText();
        vmCampos += " AND (ENT_DATA >= '"+txtVencimentoIni.getText()+"' AND ENT_DATA <= '"+txtVencimentoFim.getText()+"') ";

        if(!txtCodigoParceiroID.getText().equals(""))
        {
           vmCampos += " AND ENT_PAR_CODIGO_ID = " + txtCodigoParceiroID.getText();
           vParceiro = txtParceiro.getText();
        }



        vmCampos += " group by";
        vmCampos += " ent_data,";
        vmCampos += " ent_controle_interno,";
        vmCampos += " prod_codigo_produto,";
        vmCampos += " prod_descricao";


        vmCampos += " union";

        vmCampos += " SELECT";
        vmCampos += " sai_data as Data1,";
        vmCampos += " sai_controle_interno as controle,";
        vmCampos += " prod_codigo_produto as codigo,";
        vmCampos += " prod_descricao as descricao,";
        vmCampos += " sum(item_quantidade) * -1 as total,";
        vmCampos += " 'SAIDA' as Tipo,";
        vmCampos += " sum(item_quantidade)as qtde";

        vmCampos += " FROM SAIDA_INTERNA";
        vmCampos += " LEFT JOIN item_saida_interna ON (item_sai_codigo_id = sai_codigo_id)";
        vmCampos += " LEFT JOIN PRODUTOS ON (PROD_CODIGO_ID = ITEM_PROD_CODIGO_ID)";

        vmCampos += " WHERE SAI_EMP_CODIGO_ID = " + txtCodigoEmpresaID.getText();
        vmCampos += " AND (SAI_DATA >= '"+txtVencimentoIni.getText()+"' AND SAI_DATA <= '"+txtVencimentoFim.getText()+"') ";

        if(!txtCodigoParceiroID.getText().equals(""))
        {
           vmCampos += " AND SAI_PAR_CODIGO_ID = " + txtCodigoParceiroID.getText();
           vParceiro = txtParceiro.getText();
        }


        vmCampos += " group by";
        vmCampos += " sai_data,";
        vmCampos += " sai_controle_interno,";
        vmCampos += " prod_codigo_produto,";
        vmCampos += " prod_descricao";


        vmCampos += " ORDER BY 3,6,1   ";

    }

    private void btnPesquisaEmpresaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaEmpresaIDActionPerformed
        // TODO add your handling code here:
         variaveis.xColuna1 = "emp_codigo_id";
         variaveis.xColuna2 = "emp_nome";
         variaveis.xColuna3 = "emp_nome_fantasia";
         variaveis.xColuna4 = "emp_cnpj";
         variaveis.xColuna5 = "''";
         variaveis.xColuna6 = "''";
         variaveis.xColuna7 = "''";
         variaveis.xColuna8 = "''";
         variaveis.xColuna9 = "''";
         
         variaveis.xColunaNome1 = "Código";
         variaveis.xColunaNome2 = "Razão Social";
         variaveis.xColunaNome3 = "Fantasia";
         variaveis.xColunaNome4 = "CPF / CNPJ";
         variaveis.xColunaNome5 = "";
         variaveis.xColunaNome6 = "";
         variaveis.xColunaNome7 = "";
         variaveis.xColunaNome8 = "";
         variaveis.xColunaNome9 = "";
         
         variaveis.xColunaTamanho1 = 60;
         variaveis.xColunaTamanho2 = 450;
         variaveis.xColunaTamanho3 = 260;
         variaveis.xColunaTamanho4 = 120;
         variaveis.xColunaTamanho5 = 0;
         variaveis.xColunaTamanho6 = 0;
         variaveis.xColunaTamanho7 = 0;
         variaveis.xColunaTamanho8 = 0;
         variaveis.xColunaTamanho9 = 0;
         
         variaveis.xColunaStart = "emp_nome";
         variaveis.xColunaNomeStart = "Razão Social";
         variaveis.xTabela = "empresas";
         variaveis.xSql = ""; 
         
         FpesqPesquisa md = new FpesqPesquisa(null, true);
         Dimension d = new Dimension();   
         d.setSize(900, 480); 
         md.setSize(d);
         
         md.setTitle("Pesquisa Empresa - ENTER ou DUPLO CLICK no registro retorna dados.");

         md.setLocationRelativeTo(null);
         md.setVisible(true);

        if(!md.getRetorno().trim().equals("") ||!md.getRetorno().equals(null))
        {
          txtCodigoEmpresaID.setText((String) md.getRetorno());
        }

        txtCodigoEmpresaID.requestFocus();
        if (!txtCodigoEmpresaID.getText().equals("")) {
            String vmCampos = "*";
            String vmCondicao_Consulta = " WHERE emp_codigo_id = " + txtCodigoEmpresaID.getText();
            try {
                rs = AcessoDados.Selecao("empresas", vmCampos, vmCondicao_Consulta);
                rs.next();
                txtEmpresa.setText(rs.getString("emp_nome"));
                txtCodigoEmpresaID.requestFocus();
                rs.close();
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_btnPesquisaEmpresaIDActionPerformed

    private void txtCodigoEmpresaIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoEmpresaIDKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 114) //tecla F3 para pesquisa
        {
            btnPesquisaEmpresaIDActionPerformed(null);
        }
    }//GEN-LAST:event_txtCodigoEmpresaIDKeyPressed

    private void btnPesquisaParceiroIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaParceiroIDActionPerformed
        // TODO add your handling code here:
         variaveis.xColuna1 = "par_codigo_id";
         variaveis.xColuna2 = "par_nome_razao_social";
         variaveis.xColuna3 = "par_fantasia";
         variaveis.xColuna4 = "par_cnpj_cpf";
         variaveis.xColuna5 = "''";
         variaveis.xColuna6 = "''";
         variaveis.xColuna7 = "''";
         variaveis.xColuna8 = "''";
         variaveis.xColuna9 = "''";
         
         variaveis.xColunaNome1 = "Código";
         variaveis.xColunaNome2 = "Nome / Razão Social";
         variaveis.xColunaNome3 = "Fantasia";
         variaveis.xColunaNome4 = "CPF / CNPJ";
         variaveis.xColunaNome5 = "";
         variaveis.xColunaNome6 = "";
         variaveis.xColunaNome7 = "";
         variaveis.xColunaNome8 = "";
         variaveis.xColunaNome9 = "";
         
         variaveis.xColunaTamanho1 = 60;
         variaveis.xColunaTamanho2 = 450;
         variaveis.xColunaTamanho3 = 260;
         variaveis.xColunaTamanho4 = 120;
         variaveis.xColunaTamanho5 = 0;
         variaveis.xColunaTamanho6 = 0;
         variaveis.xColunaTamanho7 = 0;
         variaveis.xColunaTamanho8 = 0;
         variaveis.xColunaTamanho9 = 0;
         
         variaveis.xColunaStart = "par_nome_razao_social";
         variaveis.xColunaNomeStart = "Nome / Razão Social";
         variaveis.xTabela = "parceiros";
         variaveis.xSql = ""; 
         
         FpesqPesquisa md = new FpesqPesquisa(null, true);
         Dimension d = new Dimension();   
         d.setSize(900, 480); 
         md.setSize(d);
         
         md.setTitle("Pesquisa Parceiros - ENTER ou DUPLO CLICK no registro retorna dados.");

         md.setLocationRelativeTo(null);
         md.setVisible(true);

        if(!md.getRetorno().trim().equals("") ||!md.getRetorno().equals(null))
        {
          txtCodigoParceiroID.setText((String) md.getRetorno());
        }
        txtCodigoParceiroID.requestFocus();
        if (!txtCodigoParceiroID.getText().equals("")) {
            String vmCampos = "*";
            String vmCondicao_Consulta = " WHERE par_codigo_id = " + txtCodigoParceiroID.getText();
            try {
                rs = AcessoDados.Selecao("parceiros", vmCampos, vmCondicao_Consulta);
                rs.next();
                txtParceiro.setText(rs.getString("par_nome_razao_social"));
                txtCodigoParceiroID.requestFocus();
                rs.close();
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_btnPesquisaParceiroIDActionPerformed

    private void txtCodigoParceiroIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoParceiroIDKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 114) //tecla F3 para pesquisa
        {
            btnPesquisaParceiroIDActionPerformed(null);
        }
    }//GEN-LAST:event_txtCodigoParceiroIDKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void txtVencimentoFimFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVencimentoFimFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVencimentoFimFocusLost

    private void txtVencimentoIniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVencimentoIniFocusLost
        // TODO add your handling code here:


    }//GEN-LAST:event_txtVencimentoIniFocusLost

    private void txtCodigoEmpresaIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoEmpresaIDFocusGained
        // TODO add your handling code here:
        JTextField tf = (JTextField) evt.getComponent();
        tf.selectAll();
    }//GEN-LAST:event_txtCodigoEmpresaIDFocusGained

    private void txtCodigoParceiroIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoParceiroIDFocusGained
        // TODO add your handling code here:
        JTextField tf = (JTextField) evt.getComponent();
        tf.selectAll();
    }//GEN-LAST:event_txtCodigoParceiroIDFocusGained

    private void txtVencimentoIniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVencimentoIniFocusGained
        // TODO add your handling code here:
        JTextField tf = (JTextField) evt.getComponent();
        tf.selectAll();

    }//GEN-LAST:event_txtVencimentoIniFocusGained

    private void txtVencimentoFimFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVencimentoFimFocusGained
        // TODO add your handling code here:
        JTextField tf = (JTextField) evt.getComponent();
        tf.selectAll();

    }//GEN-LAST:event_txtVencimentoFimFocusGained


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                RelPedidoCliente dialog = new RelPedidoCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnPesquisaEmpresaID;
    private javax.swing.JButton btnPesquisaParceiroID;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox ddlTipoPedido;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField txtCodigoEmpresaID;
    private javax.swing.JTextField txtCodigoParceiroID;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtParceiro;
    private javax.swing.JFormattedTextField txtVencimentoFim;
    private javax.swing.JFormattedTextField txtVencimentoIni;
    // End of variables declaration//GEN-END:variables
}
