/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmEmpresa.java
 *
 * Created on 30/01/2010, 21:29:30
 */

package sae;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.*;
import Classes.claAcessoDados;
import Classes.claVariaveis;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import Classes.claFuncoes;
import Classes.claVariaveis;
import Classes.claAcessoDados;

import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.text.MaskFormatter;
import java.util.Date;
import java.text.SimpleDateFormat;

/**
 *
 * @author Thiago
 */
public class FrmEmpresa extends javax.swing.JDialog {
    claVariaveis variaveis = new claVariaveis();
    claAcessoDados AcessoDados = new claAcessoDados();
    claFuncoes funcoes = new claFuncoes();
    private ResultSet rs;
  

    /** Creates new form FrmEmpresa */
    public FrmEmpresa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        funcoes.F_AtribuirClasse(rootPane);
        btnNovo.setFocusTraversalKeysEnabled(false);
        btnAlterar.setFocusTraversalKeysEnabled(false);
        btnSalvar.setFocusTraversalKeysEnabled(false);
      }
          

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        lbStatus = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCEP = new javax.swing.JFormattedTextField();
        txtReduzido = new javax.swing.JTextField();
        txtFax = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtCNPJ = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        txtUF = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtNomeFantasia = new javax.swing.JTextField();
        txtHomePage = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtInscricaoEstadual = new javax.swing.JFormattedTextField();
        txtCodigoCidadeID = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtInscricaoMunicipal = new javax.swing.JFormattedTextField();
        txtCidadeDescricao = new javax.swing.JTextField();
        btnCodigoPesquisaCidade = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtNome_contabilista = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtCPF_contabilista = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        txtIncricaoCRC_contabilista = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtCNPJ_contabilidade = new javax.swing.JFormattedTextField();
        txtEndereco_contabilista = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtNumero_contabilista = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtCEP_contabilista = new javax.swing.JFormattedTextField();
        jLabel27 = new javax.swing.JLabel();
        txtBairro_contabilista = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtUF_contabilista = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtCodigoCidadeDesc_contabilista = new javax.swing.JTextField();
        btnCodigoPesquisaCidade1 = new javax.swing.JButton();
        txtCodigoCidadeID_contabilista = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtComplemento_contabilista = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtTelefone_contabilista = new javax.swing.JFormattedTextField();
        jLabel33 = new javax.swing.JLabel();
        txtFax_contabilista = new javax.swing.JFormattedTextField();
        jLabel34 = new javax.swing.JLabel();
        txtEmail_contabilista = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Empresas");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        lbStatus.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        lbStatus.setForeground(new java.awt.Color(153, 153, 153));
        lbStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbStatus.setText("Registro ");
        lbStatus.setToolTipText("");
        jToolBar1.add(lbStatus);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novo.gif"))); // NOI18N
        btnNovo.setToolTipText("Novo");
        btnNovo.setBorderPainted(false);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/alterar.gif"))); // NOI18N
        btnAlterar.setToolTipText("Alterar");
        btnAlterar.setBorderPainted(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluir.gif"))); // NOI18N
        btnExcluir.setToolTipText("Excluir");
        btnExcluir.setBorderPainted(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sair.gif"))); // NOI18N
        btnSair.setToolTipText("Voltar");
        btnSair.setBorderPainted(false);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Localizar.gif"))); // NOI18N
        btnPesquisar.setToolTipText("Pesquisar");
        btnPesquisar.setBorderPainted(false);
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.gif"))); // NOI18N
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.setBorderPainted(false);
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar.gif"))); // NOI18N
        btnCancelar.setToolTipText("Cancelar");
        btnCancelar.setBorderPainted(false);
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel2.setText("Nome:");
        jLabel2.setToolTipText("");

        txtCEP.setColumns(9);
        try {
            txtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCEP.setToolTipText("");
        txtCEP.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtCEP.setEnabled(false);
        txtCEP.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtCEP.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtCEP.setName("emp_cep"); // NOI18N

        txtReduzido.setColumns(15);
        txtReduzido.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtReduzido.setToolTipText("");
        txtReduzido.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtReduzido.setEnabled(false);
        txtReduzido.setName("emp_reduzido"); // NOI18N
        txtReduzido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtReduzidoKeyReleased(evt);
            }
        });

        txtFax.setColumns(13);
        try {
            txtFax.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFax.setToolTipText("");
        txtFax.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtFax.setEnabled(false);
        txtFax.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtFax.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtFax.setName("emp_fax"); // NOI18N

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel12.setText("UF:");
        jLabel12.setToolTipText("");

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel17.setText("E-mail:");
        jLabel17.setToolTipText("");

        txtComplemento.setColumns(30);
        txtComplemento.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtComplemento.setToolTipText("");
        txtComplemento.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtComplemento.setEnabled(false);
        txtComplemento.setName("emp_complemento"); // NOI18N
        txtComplemento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtComplementoKeyReleased(evt);
            }
        });

        txtNome.setColumns(50);
        txtNome.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtNome.setToolTipText("");
        txtNome.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtNome.setEnabled(false);
        txtNome.setName("emp_nome"); // NOI18N
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeKeyReleased(evt);
            }
        });

        txtCNPJ.setColumns(18);
        try {
            txtCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCNPJ.setToolTipText("");
        txtCNPJ.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtCNPJ.setEnabled(false);
        txtCNPJ.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtCNPJ.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtCNPJ.setName("emp_cnpj"); // NOI18N

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel16.setText("Fax:");
        jLabel16.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel5.setText("CNPJ:");
        jLabel5.setToolTipText("");

        txtTelefone.setColumns(13);
        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setToolTipText("");
        txtTelefone.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtTelefone.setEnabled(false);
        txtTelefone.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtTelefone.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtTelefone.setName("emp_telefone"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel10.setText("Bairro:");
        jLabel10.setToolTipText("");

        txtUF.setColumns(2);
        txtUF.setEditable(false);
        txtUF.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtUF.setToolTipText("");
        txtUF.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtUF.setFocusable(false);
        txtUF.setName(""); // NOI18N
        txtUF.setRequestFocusEnabled(false);

        txtEmail.setColumns(50);
        txtEmail.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtEmail.setToolTipText("email");
        txtEmail.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtEmail.setEnabled(false);
        txtEmail.setName("emp_email"); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel15.setText("Telefone:");
        jLabel15.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel4.setText("Reduzido:");
        jLabel4.setToolTipText("");

        txtNumero.setColumns(8);
        txtNumero.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtNumero.setToolTipText("Número");
        txtNumero.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtNumero.setEnabled(false);
        txtNumero.setName("emp_numero"); // NOI18N
        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumeroKeyReleased(evt);
            }
        });

        txtBairro.setColumns(50);
        txtBairro.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtBairro.setToolTipText("");
        txtBairro.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtBairro.setEnabled(false);
        txtBairro.setName("emp_bairro"); // NOI18N
        txtBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBairroKeyReleased(evt);
            }
        });

        txtNomeFantasia.setColumns(50);
        txtNomeFantasia.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtNomeFantasia.setToolTipText("");
        txtNomeFantasia.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtNomeFantasia.setEnabled(false);
        txtNomeFantasia.setName("emp_nome_fantasia"); // NOI18N
        txtNomeFantasia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeFantasiaKeyReleased(evt);
            }
        });

        txtHomePage.setColumns(50);
        txtHomePage.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtHomePage.setToolTipText("homepage");
        txtHomePage.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtHomePage.setEnabled(false);
        txtHomePage.setName("emp_homepage"); // NOI18N
        txtHomePage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHomePageKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel1.setText("Código:");
        jLabel1.setToolTipText("");

        lbID.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        lbID.setText("0");
        lbID.setToolTipText("ID");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel3.setText("Nome Fantasia:");
        jLabel3.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel6.setText("Inscrição Estadual:");
        jLabel6.setToolTipText("");

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel14.setText("CEP:");
        jLabel14.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel8.setText("Endereço:");
        jLabel8.setToolTipText("");

        txtInscricaoEstadual.setColumns(11);
        txtInscricaoEstadual.setToolTipText("");
        txtInscricaoEstadual.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtInscricaoEstadual.setEnabled(false);
        txtInscricaoEstadual.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtInscricaoEstadual.setName("emp_insc_estadual"); // NOI18N

        txtCodigoCidadeID.setColumns(8);
        txtCodigoCidadeID.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtCodigoCidadeID.setToolTipText("Código");
        txtCodigoCidadeID.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtCodigoCidadeID.setEnabled(false);
        txtCodigoCidadeID.setName("emp_cid_codigo_id"); // NOI18N
        txtCodigoCidadeID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoCidadeIDFocusLost(evt);
            }
        });
        txtCodigoCidadeID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoCidadeIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoCidadeIDKeyReleased(evt);
            }
        });

        txtEndereco.setColumns(50);
        txtEndereco.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtEndereco.setToolTipText("");
        txtEndereco.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtEndereco.setEnabled(false);
        txtEndereco.setName("emp_endereco"); // NOI18N
        txtEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEnderecoKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel7.setText("Inscrição Municipal:");
        jLabel7.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel11.setText("Cidade:");
        jLabel11.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel9.setText("Número:");
        jLabel9.setToolTipText("");

        txtInscricaoMunicipal.setColumns(20);
        txtInscricaoMunicipal.setToolTipText("");
        txtInscricaoMunicipal.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtInscricaoMunicipal.setEnabled(false);
        txtInscricaoMunicipal.setName("emp_insc_municipal"); // NOI18N
        txtInscricaoMunicipal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInscricaoMunicipalKeyReleased(evt);
            }
        });

        txtCidadeDescricao.setBackground(new java.awt.Color(238, 238, 238));
        txtCidadeDescricao.setColumns(30);
        txtCidadeDescricao.setEditable(false);
        txtCidadeDescricao.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtCidadeDescricao.setToolTipText("");
        txtCidadeDescricao.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtCidadeDescricao.setFocusable(false);
        txtCidadeDescricao.setName(""); // NOI18N
        txtCidadeDescricao.setRequestFocusEnabled(false);

        btnCodigoPesquisaCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.gif"))); // NOI18N
        btnCodigoPesquisaCidade.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCodigoPesquisaCidade.setEnabled(false);
        btnCodigoPesquisaCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodigoPesquisaCidadeActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel13.setText("Complemento:");
        jLabel13.setToolTipText("");

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel18.setText("Home Page:");
        jLabel18.setToolTipText("");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Contabilista", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10))); // NOI18N
        jPanel1.setToolTipText("");

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel20.setText("Nome:");
        jLabel20.setToolTipText("");

        txtNome_contabilista.setColumns(100);
        txtNome_contabilista.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtNome_contabilista.setToolTipText("");
        txtNome_contabilista.setEnabled(false);
        txtNome_contabilista.setName("emp_nome_contabil");

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel22.setText("CPF:");
        jLabel22.setToolTipText("");

        txtCPF_contabilista.setColumns(18);
        try {
            txtCPF_contabilista.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPF_contabilista.setToolTipText("");
        txtCPF_contabilista.setEnabled(false);
        txtCPF_contabilista.setName("emp_cpf_contabil");

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel23.setText("Número Inscrição CRC:");
        jLabel23.setToolTipText("");

        txtIncricaoCRC_contabilista.setColumns(15);
        txtIncricaoCRC_contabilista.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtIncricaoCRC_contabilista.setToolTipText("");
        txtIncricaoCRC_contabilista.setEnabled(false);
        txtIncricaoCRC_contabilista.setName("emp_crc_contabil");

        jLabel24.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel24.setText("CNPJ Contabilidade:");
        jLabel24.setToolTipText("");

        txtCNPJ_contabilidade.setColumns(18);
        try {
            txtCNPJ_contabilidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCNPJ_contabilidade.setToolTipText("");
        txtCNPJ_contabilidade.setEnabled(false);
        txtCNPJ_contabilidade.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtCNPJ_contabilidade.setName("emp_cnpj_contabil");

        txtEndereco_contabilista.setColumns(60);
        txtEndereco_contabilista.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtEndereco_contabilista.setToolTipText("");
        txtEndereco_contabilista.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtEndereco_contabilista.setEnabled(false);
        txtEndereco_contabilista.setName("emp_endereco_contabil"); // NOI18N
        txtEndereco_contabilista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEndereco_contabilistaKeyReleased(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel25.setText("Endereço:");
        jLabel25.setToolTipText("");

        jLabel26.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel26.setText("Número:");
        jLabel26.setToolTipText("");

        txtNumero_contabilista.setColumns(8);
        txtNumero_contabilista.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtNumero_contabilista.setToolTipText("Número");
        txtNumero_contabilista.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtNumero_contabilista.setEnabled(false);
        txtNumero_contabilista.setName("emp_numero_contabil"); // NOI18N
        txtNumero_contabilista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumero_contabilistaKeyReleased(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel28.setText("CEP:");
        jLabel28.setToolTipText("");

        txtCEP_contabilista.setColumns(9);
        try {
            txtCEP_contabilista.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCEP_contabilista.setToolTipText("");
        txtCEP_contabilista.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtCEP_contabilista.setEnabled(false);
        txtCEP_contabilista.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtCEP_contabilista.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtCEP_contabilista.setName("emp_cep_contabil"); // NOI18N

        jLabel27.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel27.setText("Bairro:");
        jLabel27.setToolTipText("");

        txtBairro_contabilista.setColumns(50);
        txtBairro_contabilista.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtBairro_contabilista.setToolTipText("");
        txtBairro_contabilista.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtBairro_contabilista.setEnabled(false);
        txtBairro_contabilista.setName("emp_bairro_contabil"); // NOI18N
        txtBairro_contabilista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBairro_contabilistaKeyReleased(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel32.setText("UF:");
        jLabel32.setToolTipText("");

        txtUF_contabilista.setColumns(2);
        txtUF_contabilista.setEditable(false);
        txtUF_contabilista.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtUF_contabilista.setToolTipText("");
        txtUF_contabilista.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtUF_contabilista.setFocusable(false);
        txtUF_contabilista.setName(""); // NOI18N
        txtUF_contabilista.setRequestFocusEnabled(false);

        jLabel31.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel31.setText("Cidade:");
        jLabel31.setToolTipText("");

        txtCodigoCidadeDesc_contabilista.setBackground(new java.awt.Color(238, 238, 238));
        txtCodigoCidadeDesc_contabilista.setColumns(30);
        txtCodigoCidadeDesc_contabilista.setEditable(false);
        txtCodigoCidadeDesc_contabilista.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtCodigoCidadeDesc_contabilista.setToolTipText("");
        txtCodigoCidadeDesc_contabilista.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtCodigoCidadeDesc_contabilista.setFocusable(false);
        txtCodigoCidadeDesc_contabilista.setName(""); // NOI18N
        txtCodigoCidadeDesc_contabilista.setRequestFocusEnabled(false);

        btnCodigoPesquisaCidade1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.gif"))); // NOI18N
        btnCodigoPesquisaCidade1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCodigoPesquisaCidade1.setEnabled(false);
        btnCodigoPesquisaCidade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodigoPesquisaCidade1ActionPerformed(evt);
            }
        });

        txtCodigoCidadeID_contabilista.setColumns(8);
        txtCodigoCidadeID_contabilista.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtCodigoCidadeID_contabilista.setToolTipText("Código");
        txtCodigoCidadeID_contabilista.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtCodigoCidadeID_contabilista.setEnabled(false);
        txtCodigoCidadeID_contabilista.setName("emp_cid_codigo_id_contabil"); // NOI18N
        txtCodigoCidadeID_contabilista.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoCidadeID_contabilistaFocusLost(evt);
            }
        });
        txtCodigoCidadeID_contabilista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoCidadeID_contabilistaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoCidadeID_contabilistaKeyReleased(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel29.setText("Complemento:");
        jLabel29.setToolTipText("");

        txtComplemento_contabilista.setColumns(30);
        txtComplemento_contabilista.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtComplemento_contabilista.setToolTipText("");
        txtComplemento_contabilista.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtComplemento_contabilista.setEnabled(false);
        txtComplemento_contabilista.setName("emp_complemento_contabil"); // NOI18N
        txtComplemento_contabilista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtComplemento_contabilistaKeyReleased(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel30.setText("Telefone:");
        jLabel30.setToolTipText("");

        txtTelefone_contabilista.setColumns(13);
        try {
            txtTelefone_contabilista.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone_contabilista.setToolTipText("");
        txtTelefone_contabilista.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtTelefone_contabilista.setEnabled(false);
        txtTelefone_contabilista.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtTelefone_contabilista.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtTelefone_contabilista.setName("emp_telefone_contabil"); // NOI18N

        jLabel33.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel33.setText("Fax:");
        jLabel33.setToolTipText("");

        txtFax_contabilista.setColumns(13);
        try {
            txtFax_contabilista.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFax_contabilista.setToolTipText("");
        txtFax_contabilista.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtFax_contabilista.setEnabled(false);
        txtFax_contabilista.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtFax_contabilista.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtFax_contabilista.setName("emp_fax_contabil"); // NOI18N

        jLabel34.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel34.setText("E-mail :");
        jLabel34.setToolTipText("");

        txtEmail_contabilista.setColumns(50);
        txtEmail_contabilista.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtEmail_contabilista.setToolTipText("email");
        txtEmail_contabilista.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtEmail_contabilista.setEnabled(false);
        txtEmail_contabilista.setName("emp_email_contabil"); // NOI18N
        txtEmail_contabilista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmail_contabilistaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel34)
                    .addComponent(jLabel25)
                    .addComponent(jLabel29)
                    .addComponent(jLabel27)
                    .addComponent(jLabel22)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtBairro_contabilista, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoCidadeID_contabilista, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCodigoPesquisaCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoCidadeDesc_contabilista, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUF_contabilista, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCPF_contabilista, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIncricaoCRC_contabilista, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCNPJ_contabilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtEndereco_contabilista, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumero_contabilista, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCEP_contabilista, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                    .addComponent(txtNome_contabilista, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtComplemento_contabilista, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefone_contabilista, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFax_contabilista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtEmail_contabilista))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome_contabilista, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCPF_contabilista, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(txtIncricaoCRC_contabilista, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(txtCNPJ_contabilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEndereco_contabilista, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25)
                        .addComponent(txtNumero_contabilista, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCEP_contabilista, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBairro_contabilista, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel32)
                                    .addComponent(txtUF_contabilista, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCodigoCidadeID_contabilista, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel31)))
                            .addComponent(txtCodigoCidadeDesc_contabilista, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnCodigoPesquisaCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtComplemento_contabilista, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFax_contabilista, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel33)
                        .addComponent(txtTelefone_contabilista, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30))
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(txtEmail_contabilista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel1))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbID, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeFantasia)
                            .addComponent(txtNome)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(88, 88, 88)
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtUF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(5, 5, 5)
                                                .addComponent(jLabel14)
                                                .addGap(109, 109, 109))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtReduzido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(txtInscricaoMunicipal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(txtNumero, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtInscricaoEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtBairro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCodigoCidadeID, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(btnCodigoPesquisaCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCidadeDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121)
                                .addComponent(txtCEP))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbID)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReduzido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInscricaoEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInscricaoMunicipal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnCodigoPesquisaCidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigoCidadeID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(txtUF, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addComponent(txtCidadeDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        if(funcoes.Permissao("001", variaveis.usuario_id, variaveis.usuario_super, this.getTitle()))
        {
        funcoes.limparTodosCampos(rootPane);
        funcoes.HabilitaCampos(rootPane, true);
        lbStatus.setText("Incluindo... ");
        txtNome.requestFocus();
        }

    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        if (txtNome.getText().equals(null) || (txtNome.getText().equals("")))
        {
            JOptionPane.showMessageDialog(null,"Selecione uma Empresa para alterar.");
            return;
        }
        if(funcoes.Permissao("002", variaveis.usuario_id, variaveis.usuario_super, this.getTitle()))
        {
        funcoes.HabilitaCampos(rootPane, true);
        lbStatus.setText(" Alterando");
        txtNome.requestFocus();
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        if(funcoes.Permissao("003", variaveis.usuario_id, variaveis.usuario_super, this.getTitle()))
        {
        funcoes.ExcluirDados(lbID.getText(), rootPane, "empresas", "emp_codigo_id");
        btnNovo.requestFocus();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        if (txtNome.getText().equals(null) || (txtNome.getText().equals("")))
        {
            JOptionPane.showMessageDialog(null,"Empresa não foi informada");
            txtNome.requestFocus();
            return;
        }
        funcoes.GravarDados(lbID.getText(), rootPane, "empresas", "emp_codigo_id",true);
        lbStatus.setText(" Registro");
        btnNovo.requestFocus();
      
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        funcoes.limparTodosCampos(rootPane);
        funcoes.HabilitaCampos(rootPane, false);
        btnNovo.requestFocus();
        lbStatus.setText(" Registro");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowActivated

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        if(funcoes.Permissao("004", variaveis.usuario_id, variaveis.usuario_super, this.getTitle()))
        {
         variaveis.xColuna1 = "emp_codigo_id";
         variaveis.xColuna2 = "emp_nome";
         variaveis.xColuna3 = "emp_nome_fantasia";
         variaveis.xColuna4 = "emp_cnpj";
         variaveis.xColuna5 = "''";
         variaveis.xColuna6 = "''";
         variaveis.xColuna7 = "''";
         variaveis.xColuna8 = "''";
         variaveis.xColuna9 = "''";
         
         variaveis.xColunaNome1 = "Código";
         variaveis.xColunaNome2 = "Razão Social";
         variaveis.xColunaNome3 = "Fantasia";
         variaveis.xColunaNome4 = "CPF / CNPJ";
         variaveis.xColunaNome5 = "";
         variaveis.xColunaNome6 = "";
         variaveis.xColunaNome7 = "";
         variaveis.xColunaNome8 = "";
         variaveis.xColunaNome9 = "";
         
         variaveis.xColunaTamanho1 = 60;
         variaveis.xColunaTamanho2 = 450;
         variaveis.xColunaTamanho3 = 260;
         variaveis.xColunaTamanho4 = 120;
         variaveis.xColunaTamanho5 = 0;
         variaveis.xColunaTamanho6 = 0;
         variaveis.xColunaTamanho7 = 0;
         variaveis.xColunaTamanho8 = 0;
         variaveis.xColunaTamanho9 = 0;
         
         variaveis.xColunaStart = "emp_nome";
         variaveis.xColunaNomeStart = "Razão Social";
         variaveis.xTabela = "empresas";
         variaveis.xSql = ""; 
         
         FpesqPesquisa md = new FpesqPesquisa(null, true);
         Dimension d = new Dimension();   
         d.setSize(900, 480); 
         md.setSize(d);
         
         md.setTitle("Pesquisa Empresa - ENTER ou DUPLO CLICK no registro retorna dados.");

         md.setLocationRelativeTo(null);
         md.setVisible(true);

       lbID.setText((String) md.getRetorno());
       if(!lbID.getText().equals(""))
       {
          String vmCampos = "*";
          String vmCondicao_Consulta = " WHERE emp_codigo_id = " + lbID.getText();
          funcoes.RetornarSelecao(rootPane,"empresas", vmCampos, vmCondicao_Consulta);
       }
       
          /*try
          {
          rs = AcessoDados.Selecao("empresas", "*", "WHERE emp_codigo_id = " + lbID.getText());
          rs.next();
          txtCNPJ.setText(rs.getString("emp_cnpj"));
          btnAlterar.requestFocus();
          rs.close();
          }catch (Exception e) {
           e.printStackTrace();
          }*/
       
      }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtEnderecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnderecoKeyReleased
        // TODO add your handling code here:
}//GEN-LAST:event_txtEnderecoKeyReleased

    private void txtInscricaoMunicipalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInscricaoMunicipalKeyReleased
        // TODO add your handling code here:
        // funcoes.ValidaNumero(txtInscricaoMunicipal);
}//GEN-LAST:event_txtInscricaoMunicipalKeyReleased

    private void txtBairroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroKeyReleased
        // TODO add your handling code here:
}//GEN-LAST:event_txtBairroKeyReleased

    private void txtNumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyReleased
        // TODO add your handling code here:
}//GEN-LAST:event_txtNumeroKeyReleased

    private void txtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyReleased
        // TODO add your handling code here:
}//GEN-LAST:event_txtNomeKeyReleased

    private void txtNomeFantasiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeFantasiaKeyReleased
        // TODO add your handling code here:
}//GEN-LAST:event_txtNomeFantasiaKeyReleased

    private void btnCodigoPesquisaCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodigoPesquisaCidadeActionPerformed
        // TODO add your handling code here:
         variaveis.xColuna1 = "cid_codigo_id";
         variaveis.xColuna2 = "cid_codigo_uf";
         variaveis.xColuna3 = "cid_uf";
         variaveis.xColuna4 = "cid_codigo_municipio";
         variaveis.xColuna5 = "cid_municipio";
         variaveis.xColuna6 = "''";
         variaveis.xColuna7 = "''";
         variaveis.xColuna8 = "''";
         variaveis.xColuna9 = "''";
         
         variaveis.xColunaNome1 = "Código";
         variaveis.xColunaNome2 = "Cód UF";
         variaveis.xColunaNome3 = "UF";
         variaveis.xColunaNome4 = "Cód. Mun.";
         variaveis.xColunaNome5 = "Município";
         variaveis.xColunaNome6 = "";
         variaveis.xColunaNome7 = "";
         variaveis.xColunaNome8 = "";
         variaveis.xColunaNome9 = "";
         
         variaveis.xColunaTamanho1 = 60;
         variaveis.xColunaTamanho2 = 60;
         variaveis.xColunaTamanho3 = 50;
         variaveis.xColunaTamanho4 = 70;
         variaveis.xColunaTamanho5 = 310;
         variaveis.xColunaTamanho6 = 0;
         variaveis.xColunaTamanho7 = 0;
         variaveis.xColunaTamanho8 = 0;
         variaveis.xColunaTamanho9 = 0;
         
         variaveis.xColunaStart = "cid_municipio";
         variaveis.xColunaNomeStart = "Município";
         variaveis.xTabela = "Cidades";
         variaveis.xSql = "";
         
         FpesqPesquisa md = new FpesqPesquisa(null, true);
         Dimension d = new Dimension();   
         d.setSize(560, 480); 
         md.setSize(d);
         
         md.setTitle("Pesquisa Cidade - ENTER ou DUPLO CLICK no registro retorna dados.");

         md.setLocationRelativeTo(null);
         md.setVisible(true);

        txtCodigoCidadeID.setText((String) md.getRetorno());
        txtCodigoCidadeID.requestFocus();
        if(!txtCodigoCidadeID.getText().equals("")) {
            String vmCampos = "*";
            String vmCondicao_Consulta = " WHERE cid_codigo_id = " + txtCodigoCidadeID.getText();
            try {
                rs = AcessoDados.Selecao("Cidades", vmCampos, vmCondicao_Consulta);
                rs.next();
                txtCidadeDescricao.setText(rs.getString("cid_municipio"));
                txtUF.setText(rs.getString("cid_uf"));
                txtComplemento.requestFocus();
                rs.close();
            }catch (Exception e) {
                e.printStackTrace();
            }

        }
}//GEN-LAST:event_btnCodigoPesquisaCidadeActionPerformed

    private void txtCodigoCidadeIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoCidadeIDKeyReleased
        // TODO add your handling code here:
}//GEN-LAST:event_txtCodigoCidadeIDKeyReleased

    private void txtCodigoCidadeIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoCidadeIDKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== 114) //tecla F3 para pesquisa
            btnCodigoPesquisaCidadeActionPerformed(null);
}//GEN-LAST:event_txtCodigoCidadeIDKeyPressed

    private void txtCodigoCidadeIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoCidadeIDFocusLost
        // TODO add your handling code here:
        //   if (txtCodigoCidadeID.getText().equals("") || txtCodigoCidadeID.getText().equals(null))
        // {
        //    txtCodigoCidadeID.setText("0");}

        if(!txtCodigoCidadeID.getText().equals("")) {
            String vmCampos = "*";
            String vmCondicao_Consulta = " WHERE cid_codigo_id = " + txtCodigoCidadeID.getText() ;

            try {
                rs = AcessoDados.Selecao("Cidades", vmCampos, vmCondicao_Consulta);
                if (!rs.next()) {
                    JOptionPane.showMessageDialog(null,"Cidade não cadastrada no sistema");
                    txtCodigoCidadeID.setText(null);
                    txtCidadeDescricao.setText(null);
                    txtCodigoCidadeID.requestFocus();
                    return;
                }
                txtCidadeDescricao.setText(rs.getString("cid_municipio"));
                txtUF.setText(rs.getString("cid_uf"));
                // txtComplemento.requestFocus();
                rs.close();
            }catch (Exception e) {
                e.printStackTrace();
            }

        } else
            txtCidadeDescricao.setText(null);
}//GEN-LAST:event_txtCodigoCidadeIDFocusLost

    private void txtReduzidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReduzidoKeyReleased
        // TODO add your handling code here:
}//GEN-LAST:event_txtReduzidoKeyReleased

    private void txtComplementoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComplementoKeyReleased
        // TODO add your handling code here:
}//GEN-LAST:event_txtComplementoKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtHomePageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHomePageKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHomePageKeyReleased

    private void txtEndereco_contabilistaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEndereco_contabilistaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndereco_contabilistaKeyReleased

    private void txtNumero_contabilistaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero_contabilistaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero_contabilistaKeyReleased

    private void txtBairro_contabilistaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairro_contabilistaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairro_contabilistaKeyReleased

    private void txtComplemento_contabilistaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComplemento_contabilistaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplemento_contabilistaKeyReleased

    private void txtCodigoCidadeID_contabilistaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoCidadeID_contabilistaFocusLost
        // TODO add your handling code here:
        if(!txtCodigoCidadeID_contabilista.getText().equals("")) {
            String vmCampos = "*";
            String vmCondicao_Consulta = " WHERE cid_codigo_id = " + txtCodigoCidadeID_contabilista.getText() ;

            try {
                rs = AcessoDados.Selecao("Cidades", vmCampos, vmCondicao_Consulta);
                if (!rs.next()) {
                    JOptionPane.showMessageDialog(null,"Cidade não cadastrada no sistema");
                    txtCodigoCidadeID_contabilista.setText(null);
                    txtCodigoCidadeDesc_contabilista.setText(null);
                    txtCodigoCidadeID_contabilista.requestFocus();
                    return;
                }
                txtCodigoCidadeDesc_contabilista.setText(rs.getString("cid_municipio"));
                txtUF.setText(rs.getString("cid_uf"));
                // txtComplemento.requestFocus();
                rs.close();
            }catch (Exception e) {
                e.printStackTrace();
            }

        } else
            txtCodigoCidadeDesc_contabilista.setText("");
        
    }//GEN-LAST:event_txtCodigoCidadeID_contabilistaFocusLost

    private void txtCodigoCidadeID_contabilistaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoCidadeID_contabilistaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== 114) //tecla F3 para pesquisa
            btnCodigoPesquisaCidade1ActionPerformed(null);

    }//GEN-LAST:event_txtCodigoCidadeID_contabilistaKeyPressed

    private void txtCodigoCidadeID_contabilistaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoCidadeID_contabilistaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoCidadeID_contabilistaKeyReleased

    private void btnCodigoPesquisaCidade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodigoPesquisaCidade1ActionPerformed
        // TODO add your handling code here:
         variaveis.xColuna1 = "cid_codigo_id";
         variaveis.xColuna2 = "cid_codigo_uf";
         variaveis.xColuna3 = "cid_uf";
         variaveis.xColuna4 = "cid_codigo_municipio";
         variaveis.xColuna5 = "cid_municipio";
         variaveis.xColuna6 = "''";
         variaveis.xColuna7 = "''";
         variaveis.xColuna8 = "''";
         variaveis.xColuna9 = "''";
         
         variaveis.xColunaNome1 = "Código";
         variaveis.xColunaNome2 = "Cód UF";
         variaveis.xColunaNome3 = "UF";
         variaveis.xColunaNome4 = "Cód. Mun.";
         variaveis.xColunaNome5 = "Município";
         variaveis.xColunaNome6 = "";
         variaveis.xColunaNome7 = "";
         variaveis.xColunaNome8 = "";
         variaveis.xColunaNome9 = "";
         
         variaveis.xColunaTamanho1 = 60;
         variaveis.xColunaTamanho2 = 60;
         variaveis.xColunaTamanho3 = 50;
         variaveis.xColunaTamanho4 = 70;
         variaveis.xColunaTamanho5 = 310;
         variaveis.xColunaTamanho6 = 0;
         variaveis.xColunaTamanho7 = 0;
         variaveis.xColunaTamanho8 = 0;
         variaveis.xColunaTamanho9 = 0;
         
         variaveis.xColunaStart = "cid_municipio";
         variaveis.xColunaNomeStart = "Município";
         variaveis.xTabela = "Cidades";
         variaveis.xSql = "";
         
         FpesqPesquisa md = new FpesqPesquisa(null, true);
         Dimension d = new Dimension();   
         d.setSize(560, 480); 
         md.setSize(d);
         
         md.setTitle("Pesquisa Cidade - ENTER ou DUPLO CLICK no registro retorna dados.");

         md.setLocationRelativeTo(null);
         md.setVisible(true);

        txtCodigoCidadeID_contabilista.setText((String) md.getRetorno());
        txtCodigoCidadeID_contabilista.requestFocus();
        if(!txtCodigoCidadeID_contabilista.getText().equals("")) {
            String vmCampos = "*";
            String vmCondicao_Consulta = " WHERE cid_codigo_id = " + txtCodigoCidadeID_contabilista.getText();
            try {
                rs = AcessoDados.Selecao("Cidades", vmCampos, vmCondicao_Consulta);
                rs.next();
                txtCodigoCidadeDesc_contabilista.setText(rs.getString("cid_municipio"));
                txtUF_contabilista.setText(rs.getString("cid_uf"));
                txtComplemento_contabilista.requestFocus();
                rs.close();
            }catch (Exception e) {
                e.printStackTrace();
            }

        }
        
    }//GEN-LAST:event_btnCodigoPesquisaCidade1ActionPerformed

    private void txtEmail_contabilistaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmail_contabilistaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail_contabilistaKeyReleased

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmEmpresa dialog = new FrmEmpresa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCodigoPesquisaCidade;
    private javax.swing.JButton btnCodigoPesquisaCidade1;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtBairro_contabilista;
    private javax.swing.JFormattedTextField txtCEP;
    private javax.swing.JFormattedTextField txtCEP_contabilista;
    private javax.swing.JFormattedTextField txtCNPJ;
    private javax.swing.JFormattedTextField txtCNPJ_contabilidade;
    private javax.swing.JFormattedTextField txtCPF_contabilista;
    private javax.swing.JTextField txtCidadeDescricao;
    private javax.swing.JTextField txtCodigoCidadeDesc_contabilista;
    private javax.swing.JTextField txtCodigoCidadeID;
    private javax.swing.JTextField txtCodigoCidadeID_contabilista;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtComplemento_contabilista;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail_contabilista;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtEndereco_contabilista;
    private javax.swing.JFormattedTextField txtFax;
    private javax.swing.JFormattedTextField txtFax_contabilista;
    private javax.swing.JTextField txtHomePage;
    private javax.swing.JTextField txtIncricaoCRC_contabilista;
    private javax.swing.JFormattedTextField txtInscricaoEstadual;
    private javax.swing.JFormattedTextField txtInscricaoMunicipal;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeFantasia;
    private javax.swing.JTextField txtNome_contabilista;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtNumero_contabilista;
    private javax.swing.JTextField txtReduzido;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JFormattedTextField txtTelefone_contabilista;
    private javax.swing.JTextField txtUF;
    private javax.swing.JTextField txtUF_contabilista;
    // End of variables declaration//GEN-END:variables

}
