/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmMenuAcesso.java
 *
 * Created on 02/01/2010, 12:25:47
 */
package sae;
import javax.swing.JOptionPane;
import Classes.claVariaveis;
import java.awt.Label;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.*;
import Classes.claAcessoDados;
import Classes.claFuncoes;
import java.sql.ResultSet;
import Relatorios.*;
import com.lowagie.text.Image;
import com.nilo.plaf.nimrod.NimRODLookAndFeel;
import com.nilo.plaf.nimrod.NimRODTheme;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Locale;
import org.jvnet.substance.SubstanceLookAndFeel;
import org.jvnet.substance.watermark.SubstanceImageWatermark;
import org.jvnet.substance.button.BaseButtonShaper;
import org.jvnet.substance.button.StandardButtonShaper;
import org.jvnet.substance.border.FlatInnerBorderPainter;
import org.jvnet.substance.utils.SubstanceConstants;
import javax.swing.JFrame;
import org.jvnet.substance.border.StandardBorderPainter;
import org.jvnet.substance.text.SubstanceFieldView;

/**
 *
 * @author Thiago
 */
public class FrmMenuAcesso extends javax.swing.JFrame {
    claVariaveis variaveis = new claVariaveis();
    claAcessoDados AcessoDados = new claAcessoDados();
    claFuncoes funcoes = new claFuncoes();
    private ResultSet rs;
    private String retorno;
    private UIManager.LookAndFeelInfo[] looks = UIManager.getInstalledLookAndFeels();
    /** Creates new form FrmMenuAcesso */
    public FrmMenuAcesso() {
        //atualiza(5);
        initComponents();
        //funcoes.F_AtribuirClasse(rootPane);
        setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        variaveis.nome_usuario = "";
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagens/window.png")).getImage());
        Date data = new Date(System.currentTimeMillis());
        SimpleDateFormat formatarDate = new SimpleDateFormat("dd-MM-yyyy");
        SelecionaEmpresa();
        lbUsuario.setText("Usuário: " + variaveis.nome_usuario + "   |  Data: " + formatarDate.format(data) + "  |  " + variaveis.empresa + " - " + variaveis.CNPJ +"  |") ;
          
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel2 = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnSAE = new javax.swing.JMenu();
        mnEmpresa = new javax.swing.JMenuItem();
        mnBackup = new javax.swing.JMenuItem();
        mnConfiguracoes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnGraficoFinanceiro = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        mnGraficoVendas = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        mnGraficoProdutos = new javax.swing.JMenuItem();
        mnGerarArquivos = new javax.swing.JMenu();
        mnSPED = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnCadastroUsuario = new javax.swing.JMenuItem();
        mnAlterarSenha = new javax.swing.JMenuItem();
        mnPermissao = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        mnTabelas = new javax.swing.JMenu();
        mnTransportadora = new javax.swing.JMenuItem();
        mnFuncionarios = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnGrupo = new javax.swing.JMenuItem();
        mnRamoAtividade = new javax.swing.JMenuItem();
        mnUnidadeMedida = new javax.swing.JMenuItem();
        mnDepartamento = new javax.swing.JMenuItem();
        mnAlmoxarifado = new javax.swing.JMenuItem();
        mnCidade = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnMensagemNota = new javax.swing.JMenuItem();
        mnCFOP = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnFormaPagamento = new javax.swing.JMenuItem();
        mnCondicaoPagamento = new javax.swing.JMenuItem();
        mnTipoDocumento = new javax.swing.JMenuItem();
        mnContasBancarias = new javax.swing.JMenuItem();
        mnAlmoxarifadoPrincipal = new javax.swing.JMenu();
        mnProduto = new javax.swing.JMenuItem();
        mnConsultaEstoque = new javax.swing.JMenuItem();
        mnEntradaNota = new javax.swing.JMenuItem();
        mnEntradaInterna = new javax.swing.JMenuItem();
        mnSaidaInterna = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnRelatorioAlmoxarifado = new javax.swing.JMenu();
        mnRelatorioEntradaSaida = new javax.swing.JMenuItem();
        mnFinanceiro = new javax.swing.JMenu();
        mnContasPagar = new javax.swing.JMenuItem();
        mnContasReceber = new javax.swing.JMenuItem();
        mnContasCorrentes = new javax.swing.JMenuItem();
        mnDuplicatas = new javax.swing.JMenuItem();
        mnRemessaRetorno = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnRelFinanceiro = new javax.swing.JMenu();
        mnRelContasReceber = new javax.swing.JMenuItem();
        mnRelContasPagar = new javax.swing.JMenuItem();
        mnRelacaoComissao = new javax.swing.JMenuItem();
        mnFaturamento = new javax.swing.JMenu();
        mnParceiros = new javax.swing.JMenuItem();
        mnPedido = new javax.swing.JMenuItem();
        mnNotaEletronica = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mnRelatoriosPedido = new javax.swing.JMenu();
        mnRelPedidoCliente = new javax.swing.JMenuItem();
        mnCompras = new javax.swing.JMenu();
        mnSolicitacaoCompra = new javax.swing.JMenuItem();
        mnColeta = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        mnRelatorioCompras = new javax.swing.JMenu();
        mnRelcaodeCompras = new javax.swing.JMenuItem();
        mnProducao = new javax.swing.JMenu();
        mnEngenharia = new javax.swing.JMenuItem();
        mnOrdemProducao = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("S.M.A Sistema de Administração Empresarial - Versão 2021 - 1.0");
        setBackground(new java.awt.Color(204, 204, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/image1.gif"))); // NOI18N
        jLabel2.setToolTipText("");
        jToolBar1.add(jLabel2);

        lbUsuario.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        lbUsuario.setForeground(new java.awt.Color(153, 153, 153));
        lbUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbUsuario.setText(" Usuário : TTC-ADMIN - 01-01-2009");
        lbUsuario.setToolTipText("");
        jToolBar1.add(lbUsuario);

        jMenuBar1.setForeground(new java.awt.Color(204, 204, 255));
        jMenuBar1.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N

        mnSAE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/planeta.jpg"))); // NOI18N

        mnEmpresa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnEmpresa.setText("Cadastro de Empresas");
        mnEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEmpresaActionPerformed(evt);
            }
        });
        mnSAE.add(mnEmpresa);

        mnBackup.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnBackup.setText("Backup Dados");
        mnBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBackupActionPerformed(evt);
            }
        });
        mnSAE.add(mnBackup);

        mnConfiguracoes.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnConfiguracoes.setText("Configurações de Sistema");
        mnConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConfiguracoesActionPerformed(evt);
            }
        });
        mnSAE.add(mnConfiguracoes);

        jMenu2.setText("Relatórios Gráficos");
        jMenu2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        mnGraficoFinanceiro.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnGraficoFinanceiro.setText("Financeiro Despesas X Receitas");
        mnGraficoFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGraficoFinanceiroActionPerformed(evt);
            }
        });
        jMenu2.add(mnGraficoFinanceiro);
        jMenu2.add(jSeparator8);

        mnGraficoVendas.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnGraficoVendas.setText("Vendas / Vendedor");
        mnGraficoVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGraficoVendasActionPerformed(evt);
            }
        });
        jMenu2.add(mnGraficoVendas);
        jMenu2.add(jSeparator9);

        mnGraficoProdutos.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnGraficoProdutos.setText("Vendas Produtos");
        mnGraficoProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGraficoProdutosActionPerformed(evt);
            }
        });
        jMenu2.add(mnGraficoProdutos);

        mnSAE.add(jMenu2);

        mnGerarArquivos.setText("SPED Fiscal");
        mnGerarArquivos.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnGerarArquivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGerarArquivosActionPerformed(evt);
            }
        });

        mnSPED.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        mnSPED.setText("Geração de Arquivo");
        mnSPED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSPEDActionPerformed(evt);
            }
        });
        mnGerarArquivos.add(mnSPED);

        mnSAE.add(mnGerarArquivos);

        jMenuBar1.add(mnSAE);

        jMenu1.setText("Acesso Sistema");
        jMenu1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        mnCadastroUsuario.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnCadastroUsuario.setText("Cadastro de Usuário");
        mnCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastroUsuarioActionPerformed1(evt);
            }
        });
        jMenu1.add(mnCadastroUsuario);

        mnAlterarSenha.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnAlterarSenha.setText("Alterar senha usuários");
        mnAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAlterarSenhaActionPerformed(evt);
            }
        });
        jMenu1.add(mnAlterarSenha);

        mnPermissao.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnPermissao.setText("Permissão / Restrição de Usuários");
        mnPermissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPermissaoActionPerformed(evt);
            }
        });
        jMenu1.add(mnPermissao);
        jMenu1.add(jSeparator11);

        jMenuItem12.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jMenuItem12.setText("Trocar Usuários");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuItem11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jMenuItem11.setText("Fechar Sistema");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuBar1.add(jMenu1);

        mnTabelas.setText("Tabelas");
        mnTabelas.setToolTipText("");
        mnTabelas.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnTabelas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        mnTransportadora.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnTransportadora.setText("Cadastro de Transportadoras");
        mnTransportadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTransportadoraActionPerformed(evt);
            }
        });
        mnTabelas.add(mnTransportadora);

        mnFuncionarios.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnFuncionarios.setText("Cadastro de Funcionários");
        mnFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFuncionariosActionPerformed(evt);
            }
        });
        mnTabelas.add(mnFuncionarios);
        mnTabelas.add(jSeparator3);

        mnGrupo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnGrupo.setText("Grupos");
        mnGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGrupoActionPerformed(evt);
            }
        });
        mnTabelas.add(mnGrupo);

        mnRamoAtividade.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnRamoAtividade.setText("Ramo de Atividade");
        mnRamoAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRamoAtividadeActionPerformed(evt);
            }
        });
        mnTabelas.add(mnRamoAtividade);

        mnUnidadeMedida.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnUnidadeMedida.setText("Unidade de Medida");
        mnUnidadeMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUnidadeMedidaActionPerformed(evt);
            }
        });
        mnTabelas.add(mnUnidadeMedida);

        mnDepartamento.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnDepartamento.setText("Departamentos");
        mnDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDepartamentoActionPerformed(evt);
            }
        });
        mnTabelas.add(mnDepartamento);

        mnAlmoxarifado.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnAlmoxarifado.setText("Almoxarifados");
        mnAlmoxarifado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAlmoxarifadoActionPerformed(evt);
            }
        });
        mnTabelas.add(mnAlmoxarifado);

        mnCidade.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnCidade.setText("Cidades");
        mnCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCidadeActionPerformed(evt);
            }
        });
        mnTabelas.add(mnCidade);
        mnTabelas.add(jSeparator4);

        mnMensagemNota.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnMensagemNota.setText("Mensagem Nota Fiscal");
        mnMensagemNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMensagemNotaActionPerformed(evt);
            }
        });
        mnTabelas.add(mnMensagemNota);

        mnCFOP.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnCFOP.setText("Cadastro de CFOP");
        mnCFOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCFOPActionPerformed(evt);
            }
        });
        mnTabelas.add(mnCFOP);
        mnTabelas.add(jSeparator5);

        mnFormaPagamento.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnFormaPagamento.setText("Formas de Pagamento");
        mnFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFormaPagamentoActionPerformed(evt);
            }
        });
        mnTabelas.add(mnFormaPagamento);

        mnCondicaoPagamento.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnCondicaoPagamento.setText("Condição de Pagamento");
        mnCondicaoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCondicaoPagamentoActionPerformed(evt);
            }
        });
        mnTabelas.add(mnCondicaoPagamento);

        mnTipoDocumento.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnTipoDocumento.setText("Tipo de Documento");
        mnTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTipoDocumentoActionPerformed(evt);
            }
        });
        mnTabelas.add(mnTipoDocumento);

        mnContasBancarias.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnContasBancarias.setText("Contas Bancárias");
        mnContasBancarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnContasBancariasActionPerformed(evt);
            }
        });
        mnTabelas.add(mnContasBancarias);

        jMenuBar1.add(mnTabelas);

        mnAlmoxarifadoPrincipal.setText("Almoxarifado");
        mnAlmoxarifadoPrincipal.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        mnProduto.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnProduto.setText("Cadastro de Produtos");
        mnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnProdutoActionPerformed(evt);
            }
        });
        mnAlmoxarifadoPrincipal.add(mnProduto);

        mnConsultaEstoque.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnConsultaEstoque.setText("Consulta Estoque");
        mnConsultaEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsultaEstoqueActionPerformed(evt);
            }
        });
        mnAlmoxarifadoPrincipal.add(mnConsultaEstoque);

        mnEntradaNota.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnEntradaNota.setText("Entrada de Notas");
        mnEntradaNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEntradaNotaActionPerformed(evt);
            }
        });
        mnAlmoxarifadoPrincipal.add(mnEntradaNota);

        mnEntradaInterna.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnEntradaInterna.setText("Entrada Interna");
        mnEntradaInterna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEntradaInternaActionPerformed(evt);
            }
        });
        mnAlmoxarifadoPrincipal.add(mnEntradaInterna);

        mnSaidaInterna.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnSaidaInterna.setText("Saída Interna");
        mnSaidaInterna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSaidaInternaActionPerformed(evt);
            }
        });
        mnAlmoxarifadoPrincipal.add(mnSaidaInterna);
        mnAlmoxarifadoPrincipal.add(jSeparator1);

        mnRelatorioAlmoxarifado.setText("Relatórios");
        mnRelatorioAlmoxarifado.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        mnRelatorioEntradaSaida.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnRelatorioEntradaSaida.setText("Relação de Entrada / Saida Produtos");
        mnRelatorioEntradaSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRelatorioEntradaSaidaActionPerformed(evt);
            }
        });
        mnRelatorioAlmoxarifado.add(mnRelatorioEntradaSaida);

        mnAlmoxarifadoPrincipal.add(mnRelatorioAlmoxarifado);

        jMenuBar1.add(mnAlmoxarifadoPrincipal);

        mnFinanceiro.setText("Financeiro");
        mnFinanceiro.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        mnContasPagar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnContasPagar.setText("Contas a Pagar");
        mnContasPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnContasPagarActionPerformed(evt);
            }
        });
        mnFinanceiro.add(mnContasPagar);

        mnContasReceber.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnContasReceber.setText("Contas a Receber");
        mnContasReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnContasReceberActionPerformed(evt);
            }
        });
        mnFinanceiro.add(mnContasReceber);

        mnContasCorrentes.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnContasCorrentes.setText("Contas Correntes");
        mnContasCorrentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnContasCorrentesActionPerformed(evt);
            }
        });
        mnFinanceiro.add(mnContasCorrentes);

        mnDuplicatas.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnDuplicatas.setText("Emissão de Duplicatas");
        mnDuplicatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDuplicatasActionPerformed(evt);
            }
        });
        mnFinanceiro.add(mnDuplicatas);

        mnRemessaRetorno.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnRemessaRetorno.setText("Remessa / Retorno Arquivo");
        mnRemessaRetorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRemessaRetornoActionPerformed(evt);
            }
        });
        mnFinanceiro.add(mnRemessaRetorno);
        mnFinanceiro.add(jSeparator2);

        mnRelFinanceiro.setText("Relatórios");
        mnRelFinanceiro.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        mnRelContasReceber.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnRelContasReceber.setText("Relação de Contas a Receber");
        mnRelContasReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRelContasReceberActionPerformed(evt);
            }
        });
        mnRelFinanceiro.add(mnRelContasReceber);

        mnRelContasPagar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnRelContasPagar.setText("Relação de Contas a Pagar");
        mnRelContasPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRelContasPagarActionPerformed(evt);
            }
        });
        mnRelFinanceiro.add(mnRelContasPagar);

        mnRelacaoComissao.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnRelacaoComissao.setText("Relação de Comissão de Vendas");
        mnRelacaoComissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRelacaoComissaoActionPerformed(evt);
            }
        });
        mnRelFinanceiro.add(mnRelacaoComissao);

        mnFinanceiro.add(mnRelFinanceiro);

        jMenuBar1.add(mnFinanceiro);

        mnFaturamento.setText("Comercial");
        mnFaturamento.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnFaturamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnFaturamentoMouseClicked(evt);
            }
        });
        mnFaturamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFaturamentoActionPerformed(evt);
            }
        });

        mnParceiros.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnParceiros.setText("Cadastro de Parceiros (Clientes / Fornecedores)");
        mnParceiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnParceirosActionPerformed(evt);
            }
        });
        mnFaturamento.add(mnParceiros);

        mnPedido.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnPedido.setText("Pedido de Venda");
        mnPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPedidoActionPerformed(evt);
            }
        });
        mnFaturamento.add(mnPedido);

        mnNotaEletronica.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnNotaEletronica.setText("Nota Fiscal Eletrônica");
        mnNotaEletronica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNotaEletronicaActionPerformed(evt);
            }
        });
        mnFaturamento.add(mnNotaEletronica);
        mnFaturamento.add(jSeparator7);

        mnRelatoriosPedido.setText("Relatórios");
        mnRelatoriosPedido.setToolTipText("");
        mnRelatoriosPedido.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        mnRelPedidoCliente.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnRelPedidoCliente.setText("Relação de Pedidos / Clientes");
        mnRelPedidoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRelPedidoClienteActionPerformed(evt);
            }
        });
        mnRelatoriosPedido.add(mnRelPedidoCliente);

        mnFaturamento.add(mnRelatoriosPedido);

        jMenuBar1.add(mnFaturamento);

        mnCompras.setText("Compras");
        mnCompras.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        mnSolicitacaoCompra.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnSolicitacaoCompra.setText("Solicitação de Compra");
        mnSolicitacaoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSolicitacaoCompraActionPerformed(evt);
            }
        });
        mnCompras.add(mnSolicitacaoCompra);

        mnColeta.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnColeta.setText("Cotação / Apuração / Ordem de Compra");
        mnColeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnColetaActionPerformed(evt);
            }
        });
        mnCompras.add(mnColeta);
        mnCompras.add(jSeparator10);

        mnRelatorioCompras.setText("Relatórios");
        mnRelatorioCompras.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        mnRelcaodeCompras.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnRelcaodeCompras.setText("Sugestão de Compras");
        mnRelcaodeCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRelcaodeComprasActionPerformed(evt);
            }
        });
        mnRelatorioCompras.add(mnRelcaodeCompras);

        mnCompras.add(mnRelatorioCompras);

        jMenuBar1.add(mnCompras);

        mnProducao.setText("Produção");
        mnProducao.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mnProducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnProducaoActionPerformed(evt);
            }
        });

        mnEngenharia.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        mnEngenharia.setText("Engenharia de Produto");
        mnEngenharia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEngenhariaActionPerformed(evt);
            }
        });
        mnProducao.add(mnEngenharia);

        mnOrdemProducao.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        mnOrdemProducao.setText("Ordem de Produção");
        mnOrdemProducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnOrdemProducaoActionPerformed(evt);
            }
        });
        mnProducao.add(mnOrdemProducao);

        jMenuBar1.add(mnProducao);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1107, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(522, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleName("S.M.A Sistema de Administração Empresarial - Versão 2021 - 1.0");
        getAccessibleContext().setAccessibleDescription("S.M.A Sistema de Administração Empresarial - Versão 2021 - 1.0");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jMenu9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu9MouseClicked
    private void jMenu9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu9ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        Object[] options = { " Sim ", " Não " };
        int confirmar = JOptionPane.showOptionDialog(null, "Confirma saída do sistema?", " Mensagem...",JOptionPane.DEFAULT_OPTION, JOptionPane. QUESTION_MESSAGE,null,options, options[1]);
        if(confirmar==0){
            System.exit(0);
        }
}//GEN-LAST:event_jMenu2MouseClicked

    private void mnContasCorrentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnContasCorrentesActionPerformed
        // TODO add your handling code here:
        FrmContaCorrente md = new FrmContaCorrente(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
}//GEN-LAST:event_mnContasCorrentesActionPerformed

    private void mnContasReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnContasReceberActionPerformed
        // TODO add your handling code here:
        FrmContasReceber md = new FrmContasReceber(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
}//GEN-LAST:event_mnContasReceberActionPerformed

    private void mnContasPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnContasPagarActionPerformed
        // TODO add your handling code here:
        FrmContasPagar md = new FrmContasPagar(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
}//GEN-LAST:event_mnContasPagarActionPerformed

    private void mnRelatorioEntradaSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRelatorioEntradaSaidaActionPerformed
        // TODO add your handling code here:
        RelEntradaSaidaProduto md = new RelEntradaSaidaProduto(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
}//GEN-LAST:event_mnRelatorioEntradaSaidaActionPerformed

    private void mnSaidaInternaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSaidaInternaActionPerformed
        // TODO add your handling code here:
        FrmSaidaInterna md = new FrmSaidaInterna(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
}//GEN-LAST:event_mnSaidaInternaActionPerformed

    private void mnEntradaInternaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEntradaInternaActionPerformed
        // TODO add your handling code here:
        FrmEntradaInterna md = new FrmEntradaInterna(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
}//GEN-LAST:event_mnEntradaInternaActionPerformed

    private void mnConsultaEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsultaEstoqueActionPerformed
        // TODO add your handling code here:
        FrmConsultaEstoque md = new FrmConsultaEstoque(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
    }//GEN-LAST:event_mnConsultaEstoqueActionPerformed

    private void mnFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFuncionariosActionPerformed
        // TODO add your handling code here:
        FrmFuncionario md = new FrmFuncionario(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
}//GEN-LAST:event_mnFuncionariosActionPerformed

    private void mnEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEmpresaActionPerformed
        // TODO add your handling code here:
        FrmEmpresa md = new FrmEmpresa(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
}//GEN-LAST:event_mnEmpresaActionPerformed

    private void mnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnProdutoActionPerformed
        // TODO add your handling code here:
        FrmProdutos md = new FrmProdutos(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
}//GEN-LAST:event_mnProdutoActionPerformed

    private void mnTransportadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTransportadoraActionPerformed
        // TODO add your handling code here:
        FrmTransportadoras md = new FrmTransportadoras(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
}//GEN-LAST:event_mnTransportadoraActionPerformed

    private void mnParceirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnParceirosActionPerformed
        // TODO add your handling code here:
        FrmParceiros md = new FrmParceiros(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
}//GEN-LAST:event_mnParceirosActionPerformed

    private void mnContasBancariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnContasBancariasActionPerformed
        // TODO add your handling code here:
        FrmContasBancarias md = new FrmContasBancarias(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
}//GEN-LAST:event_mnContasBancariasActionPerformed

    private void mnTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTipoDocumentoActionPerformed
        // TODO add your handling code here:
        FrmTipoDocumento md = new FrmTipoDocumento(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
}//GEN-LAST:event_mnTipoDocumentoActionPerformed

    private void mnCondicaoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCondicaoPagamentoActionPerformed
        // TODO add your handling code here:
        FrmCondicaoPagamento md = new FrmCondicaoPagamento(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
}//GEN-LAST:event_mnCondicaoPagamentoActionPerformed

    private void mnFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFormaPagamentoActionPerformed
        // TODO add your handling code here:
        FrmFormaPagamento md = new FrmFormaPagamento(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
}//GEN-LAST:event_mnFormaPagamentoActionPerformed

    private void mnCFOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCFOPActionPerformed
        // TODO add your handling code here:
        FrmCFOP md = new FrmCFOP(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
}//GEN-LAST:event_mnCFOPActionPerformed

    private void mnMensagemNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMensagemNotaActionPerformed
        // TODO add your handling code here:
        FrmMensagemFiscal md = new FrmMensagemFiscal(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
}//GEN-LAST:event_mnMensagemNotaActionPerformed

    private void mnCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCidadeActionPerformed
        // TODO add your handling code here:
        FrmCidades md = new FrmCidades(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
}//GEN-LAST:event_mnCidadeActionPerformed

    private void mnAlmoxarifadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAlmoxarifadoActionPerformed
        // TODO add your handling code here:
        FrmAlmoxarifados md = new FrmAlmoxarifados(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
}//GEN-LAST:event_mnAlmoxarifadoActionPerformed

    private void mnDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDepartamentoActionPerformed
        // TODO add your handling code here:
        FrmDepartamento md = new FrmDepartamento(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
}//GEN-LAST:event_mnDepartamentoActionPerformed

    private void mnUnidadeMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUnidadeMedidaActionPerformed
        // TODO add your handling code here:
        FrmUnidadeMedida md = new FrmUnidadeMedida(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
}//GEN-LAST:event_mnUnidadeMedidaActionPerformed

    private void mnRamoAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRamoAtividadeActionPerformed
        // TODO add your handling code here:
        FrmRamodeAtividade md = new FrmRamodeAtividade(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
}//GEN-LAST:event_mnRamoAtividadeActionPerformed

    private void mnGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGrupoActionPerformed
        // TODO add your handling code here:
        FrmGrupos md = new FrmGrupos(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
}//GEN-LAST:event_mnGrupoActionPerformed

    private void mnAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAlterarSenhaActionPerformed
        // TODO add your handling code here:
        FrmAlteraSenhaUsuario md = new FrmAlteraSenhaUsuario(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
}//GEN-LAST:event_mnAlterarSenhaActionPerformed

    private void mnBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBackupActionPerformed
        // TODO add your handling code here:
        FrmBackup md = new FrmBackup(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
}//GEN-LAST:event_mnBackupActionPerformed

    private void jmCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastroUsuarioActionPerformed
        // TODO add your handling code here:
        FrmUsuario md = new FrmUsuario(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
}//GEN-LAST:event_jmCadastroUsuarioActionPerformed

    private void jmCadastroUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmCadastroUsuarioMouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_jmCadastroUsuarioMouseClicked

    private void mnFaturamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFaturamentoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_mnFaturamentoActionPerformed

    private void mnFaturamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnFaturamentoMouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_mnFaturamentoMouseClicked

    private void mnPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPedidoActionPerformed
        // TODO add your handling code here:
        FrmPedido md = new FrmPedido(this, true);
        md.setLocationRelativeTo(null);

        md.setVisible(true);
}//GEN-LAST:event_mnPedidoActionPerformed

    private void mnSolicitacaoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSolicitacaoCompraActionPerformed
        // TODO add your handling code here:
        FrmSolicitacaoCompra md = new FrmSolicitacaoCompra(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);

    }//GEN-LAST:event_mnSolicitacaoCompraActionPerformed

    private void mnColetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnColetaActionPerformed
        // TODO add your handling code here:
        FrmCotacao md = new FrmCotacao(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);

    }//GEN-LAST:event_mnColetaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
          FrmSenha md = new FrmSenha(this, true);
          md.setLocationRelativeTo(null);
          md.setVisible(true);
          if(variaveis.nome_usuario.equals("")) this.dispose();
          Date data = new Date(System.currentTimeMillis());
          SimpleDateFormat formatarDate = new SimpleDateFormat("dd-MM-yyyy");
          SelecionaEmpresa();
          lbUsuario.setText("Usuário: " + variaveis.nome_usuario + "   |  Data: " + formatarDate.format(data) + "  |  " + variaveis.empresa + " - " + variaveis.CNPJ +"  |") ;
        mnCadastroUsuario.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnCadastroUsuario.getText()));
        mnBackup.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnBackup.getText()));
        mnAlterarSenha.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnAlterarSenha.getText()));
        mnPermissao.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnPermissao.getText()));
        mnGrupo.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnGrupo.getText()));
        mnRamoAtividade.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnRamoAtividade.getText()));
        mnUnidadeMedida.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnUnidadeMedida.getText()));
        mnDepartamento.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnDepartamento.getText()));
        mnAlmoxarifado.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnAlmoxarifado.getText()));
        mnCidade.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnCidade.getText()));
        mnMensagemNota.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnMensagemNota.getText()));
        mnCFOP.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnCFOP.getText()));
        mnFormaPagamento.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnFormaPagamento.getText()));
        mnCondicaoPagamento.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnCondicaoPagamento.getText()));
        mnTipoDocumento.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnTipoDocumento.getText()));
        mnContasBancarias.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnContasBancarias.getText()));
        mnParceiros.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnParceiros.getText()));
        mnTransportadora.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnTransportadora.getText()));
        mnProduto.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnProduto.getText()));
        mnEmpresa.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnEmpresa.getText()));
        mnFuncionarios.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnFuncionarios.getText()));
        mnEntradaInterna.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnEntradaInterna.getText()));
        mnSaidaInterna.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnSaidaInterna.getText()));
        mnConsultaEstoque.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnConsultaEstoque.getText()));
        mnContasPagar.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnContasPagar.getText()));
        mnContasReceber.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnContasReceber.getText()));
        mnContasCorrentes.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnContasCorrentes.getText()));
        mnPedido.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnPedido.getText()));
        mnSolicitacaoCompra.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnSolicitacaoCompra.getText()));
        mnColeta.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnColeta.getText()));
        mnEntradaNota.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnEntradaNota.getText()));
       mnRemessaRetorno.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnRemessaRetorno.getText()));
       //Relatorios
       mnRelatorioEntradaSaida.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnRelatorioEntradaSaida.getText()));
       if(!mnRelatorioEntradaSaida.isVisible())
       {
           mnRelatorioAlmoxarifado.setVisible(false);
       }else
       {
           mnRelatorioAlmoxarifado.setVisible(true);
       }


    }//GEN-LAST:event_formWindowOpened

    private void mnPermissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPermissaoActionPerformed
        // TODO add your handling code here:
        FrmPermissao md = new FrmPermissao(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);

    }//GEN-LAST:event_mnPermissaoActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        variaveis.nome_usuario = "";
        FrmSenha md = new FrmSenha(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
        if(variaveis.nome_usuario.equals("")) this.dispose();
        Date data = new Date(System.currentTimeMillis());
        SimpleDateFormat formatarDate = new SimpleDateFormat("dd-MM-yyyy");
        SelecionaEmpresa();
        lbUsuario.setText("Usuário: " + variaveis.nome_usuario + "   |  Data: " + formatarDate.format(data) + "  |  " + variaveis.empresa + " - " + variaveis.CNPJ +"  |") ;
        mnCadastroUsuario.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnCadastroUsuario.getText()));
        mnBackup.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnBackup.getText()));
        mnAlterarSenha.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnAlterarSenha.getText()));
        mnPermissao.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnPermissao.getText()));
        mnGrupo.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnGrupo.getText()));
        mnRamoAtividade.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnRamoAtividade.getText()));
        mnUnidadeMedida.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnUnidadeMedida.getText()));
        mnDepartamento.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnDepartamento.getText()));
        mnAlmoxarifado.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnAlmoxarifado.getText()));
        mnCidade.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnCidade.getText()));
        mnMensagemNota.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnMensagemNota.getText()));
        mnCFOP.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnCFOP.getText()));
        mnFormaPagamento.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnFormaPagamento.getText()));
        mnCondicaoPagamento.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnCondicaoPagamento.getText()));
        mnTipoDocumento.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnTipoDocumento.getText()));
        mnContasBancarias.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnContasBancarias.getText()));
        mnParceiros.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnParceiros.getText()));
        mnTransportadora.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnTransportadora.getText()));
        mnProduto.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnProduto.getText()));
        mnEmpresa.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnEmpresa.getText()));
        mnFuncionarios.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnFuncionarios.getText()));
        mnEntradaInterna.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnEntradaInterna.getText()));
        mnSaidaInterna.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnSaidaInterna.getText()));
        mnConsultaEstoque.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnConsultaEstoque.getText()));
        mnContasPagar.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnContasPagar.getText()));
        mnContasReceber.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnContasReceber.getText()));
        mnContasCorrentes.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnContasCorrentes.getText()));
        mnPedido.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnPedido.getText()));
        mnSolicitacaoCompra.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnSolicitacaoCompra.getText()));
        mnColeta.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnColeta.getText()));
        mnEntradaNota.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnEntradaNota.getText()));
        mnRemessaRetorno.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnRemessaRetorno.getText()));
       //Relatorios
       mnRelatorioEntradaSaida.setVisible(funcoes.PermissaoMenu(variaveis.usuario_id, variaveis.usuario_super, mnRelatorioEntradaSaida.getText()));
       if(!mnRelatorioEntradaSaida.isVisible())
       {
           mnRelatorioAlmoxarifado.setVisible(false);
       }else
       {
           mnRelatorioAlmoxarifado.setVisible(true);
       }





    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void mnCadastroUsuarioActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastroUsuarioActionPerformed1
        // TODO add your handling code here:
        FrmUsuario md = new FrmUsuario(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
    }//GEN-LAST:event_mnCadastroUsuarioActionPerformed1

    private void mnRemessaRetornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRemessaRetornoActionPerformed
        // TODO add your handling code here:
        FrmRemessaRetorno md = new FrmRemessaRetorno(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);

    }//GEN-LAST:event_mnRemessaRetornoActionPerformed

    private void mnNotaEletronicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNotaEletronicaActionPerformed
        // TODO add your handling code here:
        FrmNotaEletronica md = new FrmNotaEletronica(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
    }//GEN-LAST:event_mnNotaEletronicaActionPerformed

    private void mnEntradaNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEntradaNotaActionPerformed
        // TODO add your handling code here:
        FrmEntradaNotas md = new FrmEntradaNotas(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
        
    }//GEN-LAST:event_mnEntradaNotaActionPerformed

    private void mnProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnProducaoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mnProducaoActionPerformed

    private void mnEngenhariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEngenhariaActionPerformed
        // TODO add your handling code here:
        FrmEngenhariaDeProdutos md = new FrmEngenhariaDeProdutos(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
    }//GEN-LAST:event_mnEngenhariaActionPerformed

    private void mnOrdemProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnOrdemProducaoActionPerformed
        // TODO add your handling code here:
        FrmOrdemProducaoPedido md = new FrmOrdemProducaoPedido(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);

    }//GEN-LAST:event_mnOrdemProducaoActionPerformed

    private void mnDuplicatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDuplicatasActionPerformed
        // TODO add your handling code here:
        FrmDuplicatas md = new FrmDuplicatas(null, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
        
    }//GEN-LAST:event_mnDuplicatasActionPerformed

    private void mnRelPedidoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRelPedidoClienteActionPerformed
        // TODO add your handling code here:
        RelPedidoCliente md = new RelPedidoCliente(null, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
    }//GEN-LAST:event_mnRelPedidoClienteActionPerformed

    private void mnRelContasReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRelContasReceberActionPerformed
        // TODO add your handling code here:
        RelContasReceber md = new RelContasReceber(null, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);

    }//GEN-LAST:event_mnRelContasReceberActionPerformed

    private void mnRelContasPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRelContasPagarActionPerformed
        // TODO add your handling code here:
        RelContasPagar md = new RelContasPagar(null, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);

    }//GEN-LAST:event_mnRelContasPagarActionPerformed

    private void mnRelacaoComissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRelacaoComissaoActionPerformed
        // TODO add your handling code here:
        RelComissao md = new RelComissao(null, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);

    }//GEN-LAST:event_mnRelacaoComissaoActionPerformed

    private void mnGerarArquivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGerarArquivosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mnGerarArquivosActionPerformed

    private void mnSPEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSPEDActionPerformed
        // TODO add your handling code here:
        FrmSPEDFiscal md = new FrmSPEDFiscal(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);

    }//GEN-LAST:event_mnSPEDActionPerformed

    private void mnGraficoFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGraficoFinanceiroActionPerformed
        // TODO add your handling code here:
        RelGrafico md = new RelGrafico(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);

    }//GEN-LAST:event_mnGraficoFinanceiroActionPerformed

    private void mnGraficoVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGraficoVendasActionPerformed
        // TODO add your handling code here:
        RelGraficoVendas md = new RelGraficoVendas(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);

    }//GEN-LAST:event_mnGraficoVendasActionPerformed

    private void mnRelcaodeComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRelcaodeComprasActionPerformed
        // TODO add your handling code here:
        RelSugestaoCompras md = new RelSugestaoCompras(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);

    }//GEN-LAST:event_mnRelcaodeComprasActionPerformed

    private void mnGraficoProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGraficoProdutosActionPerformed
        // TODO add your handling code here:
        GraficoVendaProdutos md = new GraficoVendaProdutos(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);

    }//GEN-LAST:event_mnGraficoProdutosActionPerformed

    private void mnConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConfiguracoesActionPerformed
        // TODO add your handling code here:
        FrmConfiguracao md = new FrmConfiguracao(this, true);
        md.setLocationRelativeTo(null);
        md.setVisible(true);
    }//GEN-LAST:event_mnConfiguracoesActionPerformed
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) throws UnsupportedLookAndFeelException, MalformedURLException {
       UIManager.setLookAndFeel( new com.nilo.plaf.nimrod.NimRODLookAndFeel());
       String Caminho = new File("SAE.theme").getAbsolutePath();
      // URL temaURL = new URL("http://www.mtds.com.br/SAE.theme");
       //NimRODTheme nt = new NimRODTheme(temaURL);
       NimRODTheme nt = new NimRODTheme(Caminho);
       NimRODLookAndFeel nf = new NimRODLookAndFeel();
       nf.setCurrentTheme( nt);
       UIManager.setLookAndFeel( nf);     
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           new FrmMenuAcesso().setVisible(true);
            }
        });
     }
     public void SelecionaEmpresa()
    {

        String vmCampos = "*";

        String vmCondicao_Consulta = "";
        vmCondicao_Consulta = " where emp_codigo_id = 1";
        try
        {
         rs = AcessoDados.Selecao("empresas", vmCampos, vmCondicao_Consulta);
         rs.next();
         variaveis.empresa = rs.getString("emp_nome");
         variaveis.CNPJ = rs.getString("emp_cnpj");
         rs.close();

         }catch (Exception e) {
           JOptionPane.showMessageDialog(null, e.getMessage(), "Aviso", JOptionPane.ERROR_MESSAGE);
        }


    }

     @SuppressWarnings("unchecked")
        public void atualiza(int i){
           try {
           UIManager.setLookAndFeel(looks[i].getClassName());
           SwingUtilities.updateComponentTreeUI(this);
           }catch(Exception e) {
           e.printStackTrace();
           }
         }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JMenuItem mnAlmoxarifado;
    private javax.swing.JMenu mnAlmoxarifadoPrincipal;
    private javax.swing.JMenuItem mnAlterarSenha;
    private javax.swing.JMenuItem mnBackup;
    private javax.swing.JMenuItem mnCFOP;
    private javax.swing.JMenuItem mnCadastroUsuario;
    private javax.swing.JMenuItem mnCidade;
    private javax.swing.JMenuItem mnColeta;
    private javax.swing.JMenu mnCompras;
    private javax.swing.JMenuItem mnCondicaoPagamento;
    private javax.swing.JMenuItem mnConfiguracoes;
    private javax.swing.JMenuItem mnConsultaEstoque;
    private javax.swing.JMenuItem mnContasBancarias;
    private javax.swing.JMenuItem mnContasCorrentes;
    private javax.swing.JMenuItem mnContasPagar;
    private javax.swing.JMenuItem mnContasReceber;
    private javax.swing.JMenuItem mnDepartamento;
    private javax.swing.JMenuItem mnDuplicatas;
    private javax.swing.JMenuItem mnEmpresa;
    private javax.swing.JMenuItem mnEngenharia;
    private javax.swing.JMenuItem mnEntradaInterna;
    private javax.swing.JMenuItem mnEntradaNota;
    private javax.swing.JMenu mnFaturamento;
    private javax.swing.JMenu mnFinanceiro;
    private javax.swing.JMenuItem mnFormaPagamento;
    private javax.swing.JMenuItem mnFuncionarios;
    private javax.swing.JMenu mnGerarArquivos;
    private javax.swing.JMenuItem mnGraficoFinanceiro;
    private javax.swing.JMenuItem mnGraficoProdutos;
    private javax.swing.JMenuItem mnGraficoVendas;
    private javax.swing.JMenuItem mnGrupo;
    private javax.swing.JMenuItem mnMensagemNota;
    private javax.swing.JMenuItem mnNotaEletronica;
    private javax.swing.JMenuItem mnOrdemProducao;
    private javax.swing.JMenuItem mnParceiros;
    private javax.swing.JMenuItem mnPedido;
    private javax.swing.JMenuItem mnPermissao;
    private javax.swing.JMenu mnProducao;
    private javax.swing.JMenuItem mnProduto;
    private javax.swing.JMenuItem mnRamoAtividade;
    private javax.swing.JMenuItem mnRelContasPagar;
    private javax.swing.JMenuItem mnRelContasReceber;
    private javax.swing.JMenu mnRelFinanceiro;
    private javax.swing.JMenuItem mnRelPedidoCliente;
    private javax.swing.JMenuItem mnRelacaoComissao;
    private javax.swing.JMenu mnRelatorioAlmoxarifado;
    private javax.swing.JMenu mnRelatorioCompras;
    private javax.swing.JMenuItem mnRelatorioEntradaSaida;
    private javax.swing.JMenu mnRelatoriosPedido;
    private javax.swing.JMenuItem mnRelcaodeCompras;
    private javax.swing.JMenuItem mnRemessaRetorno;
    private javax.swing.JMenu mnSAE;
    private javax.swing.JMenuItem mnSPED;
    private javax.swing.JMenuItem mnSaidaInterna;
    private javax.swing.JMenuItem mnSolicitacaoCompra;
    private javax.swing.JMenu mnTabelas;
    private javax.swing.JMenuItem mnTipoDocumento;
    private javax.swing.JMenuItem mnTransportadora;
    private javax.swing.JMenuItem mnUnidadeMedida;
    // End of variables declaration//GEN-END:variables

}
